import type { StringCatalog } from '../i18n'

export const strings: StringCatalog = {
  // ─── Onboarding ────────────────────────────────────────────────────────────
  'onboarding.hello': "Hi! I'm Wispucci AI.",
  'onboarding.subtitle': 'Your personal assistant for focus and progress.\nEverything runs locally — no one sees our conversations.',
  'onboarding.namePlaceholder': "What's your name?",
  'onboarding.continue': 'Continue',
  'onboarding.importantQuestion': '{name}, an important question.',
  'onboarding.adhdQuestion': 'Do you have ADHD or issues with motivation/focus?',
  'onboarding.adhdHint': 'This helps me be gentler and more adaptive with you.',
  'onboarding.adhdYes': 'Yes, I need empathetic mode',
  'onboarding.adhdNo': "No, I'm fine with normal mode",
  'onboarding.languageTitle': 'Preferred language?',
  'onboarding.languageHint': 'Wispucci AI will respond in your chosen language',
  'onboarding.start': "Let's begin!",
  'onboarding.defaultReward1': 'Favorite music 🎵',
  'onboarding.defaultReward2': '5 min break ☕',
  'onboarding.defaultReward3': 'Funny meme 😂',

  // ─── Energy Prompt ──────────────────────────────────────────────────────────
  'energy.greeting': 'Good morning, {name}!',
  'energy.question': 'How is your energy level today?',
  'energy.confirm': 'Confirm ({level}/10)',
  'energy.skip': 'Skip',
  'energy.1': 'Very bad',
  'energy.2': 'Bad',
  'energy.3': 'Weak',
  'energy.4': 'Meh',
  'energy.5': 'OK',
  'energy.6': 'Decent',
  'energy.7': 'Good',
  'energy.8': 'Very good',
  'energy.9': 'Excellent',
  'energy.10': 'MAX!',

  // ─── Greetings (time of day) ───────────────────────────────────────────────
  'greeting.night': 'Good night, {name}.',
  'greeting.morning': 'Good morning, {name}.',
  'greeting.afternoon': 'Good afternoon, {name}.',
  'greeting.evening': 'Good evening, {name}.',

  // ─── Floating Menu ─────────────────────────────────────────────────────────
  'menu.tasks': 'Tasks',
  'menu.games': 'Games',
  'menu.focus': 'Focus',
  'menu.teacher': 'Teacher',
  'menu.memory': 'Memory',
  'menu.achievements': 'Achievements',
  'menu.settings': 'Settings',
  'menu.friends': 'Friends',

  // ─── Sidebar ───────────────────────────────────────────────────────────────
  'sidebar.tasks': 'Tasks',
  'sidebar.stats': 'Stats',
  'sidebar.newTask': 'New task...',
  'sidebar.noTasks': 'No tasks yet. Add one!',

  // ─── Chat ──────────────────────────────────────────────────────────────────
  'chat.placeholder': 'Type a message...',
  'chat.welcome': "Hi, I'm Wispucci AI — your personal focus assistant. Ask me anything, send me code, or just say how you're feeling today.",
  'chat.thinking': 'Thinking...',
  'chat.error': 'Something went wrong. Try again.',
  'chat.limitReached': 'Daily message limit reached. Come back tomorrow or upgrade to Premium for unlimited chat.',

  // ─── Course Creator ────────────────────────────────────────────────────────
  'creator.title': 'Create a course',
  'creator.placeholder': 'What do you want to learn?',
  'creator.generate': 'Generate',
  'creator.generating': 'Generating...',
  'creator.done': 'Course created!',
  'creator.goToCourse': 'Go to course',
  'creator.blocked': "Couldn't generate the course right now.",
  'creator.back': '← Back',
  'creator.suggestion.python': 'Python',
  'creator.suggestion.english': 'English B2',
  'creator.suggestion.investing': 'Investing',
  'creator.suggestion.uiux': 'UI/UX',
  'creator.suggestion.marketing': 'Marketing',
  'creator.suggestion.ml': 'ML',
  'creator.suggestion.adhd': 'ADHD',
  'creator.suggestion.rust': 'Rust',
  'creator.suggestion.crypto': 'Crypto',

  // ─── Course View ───────────────────────────────────────────────────────────
  'course.modules': 'Modules',
  'course.lessons': 'Lessons',
  'course.completed': 'Completed',
  'course.locked': 'Locked',
  'course.startLesson': 'Start lesson',
  'course.continueLesson': 'Continue',
  'course.back': '← Back to courses',
  'course.noContent': 'No content yet.',

  // ─── Lesson Viewer / Quiz ──────────────────────────────────────────────────
  'lesson.loading': 'Preparing lesson...',
  'lesson.readConfirm': "I'VE READ IT",
  'lesson.startTest': 'Start test',
  'lesson.quiz.correct': 'Correct!',
  'lesson.quiz.wrong': 'Not quite.',
  'lesson.quiz.next': 'Next',
  'lesson.quiz.finish': 'Finish',
  'lesson.quiz.score': 'Score: {score}/{total}',

  // ─── Teacher Mode ──────────────────────────────────────────────────────────
  'teacher.preparing': "Still preparing the teacher's explanation...",
  'teacher.readConfirm': "I've read it — start test",
  'teacher.limitNotice': 'Limit reached',
  'teacher.back': '← Back',

  // ─── Lesson Support Panel ──────────────────────────────────────────────────
  'support.howWell': 'How well did you understand?',
  'support.score': '{score}/10',
  'support.clarify': 'Ask a question',
  'support.clarifyPlaceholder': 'What was unclear?',
  'support.flashcards': 'Flashcards',
  'support.continueTest': 'Continue to test',
  'support.startTest': 'Start test',
  'support.needScore7': 'You need at least 7/10 to continue.',
  'support.recallTitle': 'Quick recall',

  // ─── Flashcards ────────────────────────────────────────────────────────────
  'flashcard.noCards': 'No flashcards',
  'flashcard.back': '← Back',
  'flashcard.tap': 'Tap to reveal',
  'flashcard.easy': 'Easy ✅',
  'flashcard.medium': 'Medium 🤔',
  'flashcard.hard': "Didn't know 😅",
  'flashcard.done': 'Session complete!',
  'flashcard.accuracy': '{percent}% accuracy',

  // ─── Achievements ──────────────────────────────────────────────────────────
  'achievements.title': 'Achievements',
  'achievements.subtitle': 'See your exact progress toward the next unlock',
  'achievements.level': 'Level {level}',
  'achievements.levelLabel': 'LEVEL',
  'achievements.xp': '{xp} XP',
  'achievements.streak': '{days} day streak',
  'achievements.lessons': '{count} lessons',
  'achievements.courses': '{count} courses',
  'achievements.words': '{count} words',
  'achievements.time': '{minutes} min',
  'achievements.nextMilestone': 'Next: {target}',
  'achievements.lessonsTrack': 'LESSONS',
  'achievements.lessonsUnit': 'lessons',
  'achievements.lessonsLeft': '{count} lessons until next milestone',
  'achievements.milestoneHit': 'Milestone reached. Next one in {size} lessons.',
  'achievements.coursesTrack': 'COURSES',
  'achievements.coursesUnit': 'courses',
  'achievements.coursesLeft': '{count} courses until next achievement',
  'achievements.wordsTrack': 'WORDS',
  'achievements.wordsUnit': 'words',
  'achievements.wordsLeft': '{count} words until next achievement',
  'achievements.timeTrack': 'TIME',
  'achievements.timeUnit': 'minutes',
  'achievements.timeLeft': '{count} minutes until next achievement',
  'achievements.allUnlocked': 'All achievements unlocked',
  'achievements.totalBadges': 'Total badges unlocked: {count}',
  'achievements.bonusXP': 'Bonus XP earned: {xp}',

  // ─── Settings ──────────────────────────────────────────────────────────────
  'settings.title': 'Settings',
  'settings.plan': 'Plan',
  'settings.activeWindow': 'Active Window',
  'settings.coursesPerMonth': 'COURSES / MONTH',
  'settings.coursesPer2h': 'COURSES / 2H',
  'settings.chatPerDay': 'CHAT / DAY',
  'settings.lessonsPer2h': 'LESSONS / 2H',
  'settings.lessonsPerMonth': 'LESSONS / MONTH',
  'settings.flashcards': 'FLASHCARDS',
  'settings.pdfExport': 'PDF EXPORT',
  'settings.yes': 'YES',
  'settings.no': 'NO',
  'settings.unlimited': '∞',
  'settings.active': 'ACTIVE',
  'settings.planLabel': 'PLAN',
  'settings.tokenSources': 'TOKEN-CONSUMING SOURCES',
  'settings.psychFrame': 'PSYCHOLOGICAL FRAMING',
  'settings.noTraffic': 'Not enough AI traffic for comparison yet.',
  'settings.clearChat': 'Clear chat history',
  'settings.clearConfirm': 'Cleared!',
  'settings.language': 'Language',
  'settings.tier.free': 'Free',
  'settings.tier.premium': 'Premium',

  // ─── Top Indicator ─────────────────────────────────────────────────────────
  'indicator.chatExhausted': 'CHAT EXHAUSTED',
  'indicator.chatRemaining': 'CHAT {remaining} / {limit} LEFT',
  'indicator.messagesLeft': '{count} messages left today',
  'indicator.messagesExhausted': 'CHAT EXHAUSTED · resets tomorrow',
  'indicator.lessonMilestoneHit': 'Small milestone reached',
  'indicator.lessonsUntilMilestone': '{count} lessons until next milestone',

  // ─── Focus Mode ────────────────────────────────────────────────────────────
  'focus.deepWork': 'Deep Work',
  'focus.sprint': 'Sprint',
  'focus.flow': 'Flow',
  'focus.custom': 'Custom',
  'focus.start': 'Start',
  'focus.pause': 'Pause',
  'focus.resume': 'Resume',
  'focus.stop': 'Stop',
  'focus.sessionComplete': 'Session complete!',
  'focus.back': '← Back',

  // ─── Pomodoro ──────────────────────────────────────────────────────────────
  'pomodoro.work': 'Focus time',
  'pomodoro.break': 'Break time',
  'pomodoro.sessions': '{count} sessions',
  'pomodoro.wellDone': 'Well done! Take a break.',
  'pomodoro.breakOver': 'Break is over. Let\'s continue!',
  'pomodoro.focusActivated': 'Focus mode activated. Let\'s work!',
  'pomodoro.breakStarted': 'Break started.',
  'pomodoro.back': '← Back',

  // ─── Body Doubling ─────────────────────────────────────────────────────────
  'companion.together': 'together',
  'companion.exit': '← exit',
  'companion.main': 'We are together, {name}.',
  'companion.mainNoName': 'We are together.',
  'companion.sub': 'Work in peace. I am here.',
  'companion.phrases.0': 'I am here',
  'companion.phrases.1': 'You are doing well',
  'companion.phrases.2': 'Breathe',
  'companion.phrases.3': 'You are not alone',
  'companion.phrases.4': 'Take a break if you need',
  'companion.phrases.5': 'You are on the right path',
  'companion.phrases.6': 'Everything you do matters',
  'companion.phrases.7': 'I am right here',
  'companion.phrases.8': 'Thinking of you',
  'companion.phrases.9': 'Go easy',

  // ─── Dopamine Menu ─────────────────────────────────────────────────────────
  'dopamine.youtube': '15 min YouTube',
  'dopamine.game': '20 min gaming',
  'dopamine.walk': 'Walk outside',
  'dopamine.snack': 'Favorite snack',
  'dopamine.music': 'Listen to music',
  'dopamine.social': '10 min social media',
  'dopamine.nap': '20 min power nap',
  'dopamine.draw': 'Draw something',
  'dopamine.stretch': 'Stretching / Yoga',
  'dopamine.chat': 'Talk to someone',
  'dopamine.coffee': 'Coffee break',
  'dopamine.custom': 'Custom reward',
  'dopamine.enjoy': 'Enjoy!',
  'dopamine.deserved': 'You earned it. Relax.',
  'dopamine.backToWork': 'Back to work',
  'dopamine.congrats': 'Congrats!',

  // ─── Career Mirror ─────────────────────────────────────────────────────────
  'career.title': 'Career Mirror',
  'career.loading': 'Generating projection...',
  'career.back': '← Back',

  // ─── Daily Summary ─────────────────────────────────────────────────────────
  'daily.title': 'Daily Summary',
  'daily.loading': 'Generating summary...',
  'daily.back': '← Back',

  // ─── Brain Games ───────────────────────────────────────────────────────────
  'games.title': 'Brain Games',
  'games.back': '← Back',
  'games.mathSpeed': 'Math Speed',
  'games.memoryTiles': 'Memory Tiles',
  'games.patternMatch': 'Pattern Match',
  'games.reactionTime': 'Reaction Time',
  'games.wordScramble': 'Word Scramble',
  'games.colorStroop': 'Color Stroop',
  'games.todayPoints': 'Today',
  'games.totalPoints': 'Total',
  'games.leaderboard': 'Leaderboard',
  'games.difficulty': 'Difficulty',

  // ─── Memory Panel ──────────────────────────────────────────────────────────
  'memory.stable': 'Stable',
  'memory.stableHint': 'Facts that stay (who you are, what you love, goals)',
  'memory.moments': 'Moments',
  'memory.momentsHint': 'Emotionally tagged moments (victories, struggles, discoveries)',
  'memory.session': 'Session',
  'memory.sessionHint': 'Context from this session (expires in 6h if not important)',
  'memory.all': 'All',
  'memory.add': '+ Add',
  'memory.addNew': 'Add new',
  'memory.remember': 'Remember',
  'memory.placeholder': 'Ex: I work best in the morning · I want to finish the book by Monday · Big deadlines stress me',
  'memory.title': 'Our Memory',
  'memory.subtitle': 'Here you can see everything I remember about you. It\'s not a secret — it\'s yours. You can delete anything, anytime.',
  'memory.tagline': 'what I remember',
  'memory.empty': 'No memories yet.',

  // ─── Levels ────────────────────────────────────────────────────────────────
  'level.1': 'Beginner',
  'level.2': 'Curious',
  'level.3': 'Consistent',
  'level.4': 'Focused',
  'level.5': 'Dedicated',
  'level.6': 'Performer',
  'level.7': 'Expert',
  'level.8': 'Master',

  // ─── Badges ────────────────────────────────────────────────────────────────
  'badge.first_session': 'First session',
  'badge.streak_3': '3 days in a row',
  'badge.streak_7': '7 days on fire',
  'badge.streak_30': '30 days legendary',
  'badge.level_3': 'Reached level 3',
  'badge.level_5': 'Reached level 5',
  'badge.xp_500': '500 XP',
  'badge.xp_1000': '1000 XP',
  'badge.first_course': 'Started first course',
  'badge.course_complete': 'Completed a course',
  'badge.course_1': 'Completed 1 course',
  'badge.course_3': 'Completed 3 courses',
  'badge.course_5': 'Completed 5 courses',
  'badge.course_10': 'Completed 10 courses',
  'badge.words_200': 'Reached 200 words',
  'badge.words_1000': 'Reached 1000 words',
  'badge.words_5000': 'Reached 5000 words',
  'badge.words_15000': 'Reached 15000 words',
  'badge.time_30': '30 minutes in app',
  'badge.time_120': '2 hours in app',
  'badge.time_600': '10 hours in app',
  'badge.time_1800': '30 hours in app',

  // ─── Moods ─────────────────────────────────────────────────────────────────
  'mood.happy': 'Happy',
  'mood.excited': 'Excited',
  'mood.think': 'Thoughtful',
  'mood.sleepy': 'Sleepy',
  'mood.sad': 'Sad',
  'mood.love': 'Grateful',
  'mood.focus': 'Focused',

  // ─── Crisis ────────────────────────────────────────────────────────────────
  'crisis.response': `I understand you're going through a very difficult moment. You are not alone in this.

Please call one of these numbers NOW — trained people are listening, for free, 24/7:
• USA: 988 (Suicide & Crisis Lifeline)
• UK: 116 123 (Samaritans)
• International: findahelpline.com

You don't have to go through this alone. These people are trained to help.`,

  // ─── Tier Limit Messages ───────────────────────────────────────────────────
  'limits.courseWindow': '🧠 ACTIVE CONSOLIDATION\n\nYou\'ve already created {limit} courses in the last 2 hours on the {label} plan. Pause and let existing courses settle.\n\nCome back in {reset} or continue one of the courses you\'ve already started.',
  'limits.courseMonth': '📚 MONTHLY COURSE LIMIT\n\nYou\'ve reached the monthly limit of {limit} courses on the {label} plan.\n\nYou can continue existing courses and get new slots next month.',
  'limits.lessonWindow': '📚 CONSOLIDATION PAUSE\n\nYou\'ve already opened {limit} new lessons in the last 2 hours on the {label} plan. Continue what you started and come back after reset.\n\nNext new slot opens in {reset}.',
  'limits.lessonMonth': '🧩 MONTHLY LESSON LIMIT\n\nYou\'ve reached the monthly limit of {limit} lessons on the {label} plan.\n\nYou can continue existing lessons and get new slots next month.',
  'limits.chatBudget': '💬 CHAT LIMIT REACHED\n\nYou\'ve used all {limit} daily messages on the {label} plan.\n\nMessages reset tomorrow. Upgrade to Premium for unlimited chat.',
  'limits.chatExhausted': 'CHAT EXHAUSTED · resets tomorrow',

  // ─── Tier Notes ────────────────────────────────────────────────────────────
  'tierNote.courses': 'Courses have two guards: a pacing cap per 2 hours and a volume cap per month. The first stops impulsive spam, the second keeps economics in control.',
  'tierNote.chat': 'Chat is the only blocking AI budget. Courses and lessons use telemetry for cost, not token locks.',
  'tierNote.lessons': 'Lessons have both a 2-hour cap and a monthly cap. Re-entering the same lesson does not consume a new slot.',
  'tierNote.flashcardsUnlimited': 'This plan does not limit the total number of flashcards.',
  'tierNote.flashcardsLimited': 'The flashcard limit keeps the system dense and repeatable, not a forgotten card warehouse.',
  'tierNote.pdfExportYes': 'PDF export remains active when the export surface is open in the UI.',
  'tierNote.pdfExportNo': 'PDF export is locked on this plan as a convenience feature, not a core learning feature.',

  // ─── Overlay / Tray ────────────────────────────────────────────────────────
  'overlay.newLesson': "Let's learn something new!",
  'overlay.progress': 'Progress is made step by step.',
  'overlay.youGotThis': 'You got this!',
  'overlay.keepGoing': 'Keep going!',
  'tray.show': 'Show Wispucci AI',
  'tray.quit': 'Quit',

  // ─── Game colors (Stroop) ──────────────────────────────────────────────────
  'color.red': 'RED',
  'color.blue': 'BLUE',
  'color.green': 'GREEN',
  'color.yellow': 'YELLOW',
  'color.orange': 'ORANGE',

  // ─── Themes ────────────────────────────────────────────────────────────────
  'theme.forest': 'Forest',

  // ─── Common ────────────────────────────────────────────────────────────────
  'common.back': '← Back',
  'common.close': 'Close',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.loading': 'Loading...',
  'common.noData': 'No data yet.',

  // ─── AI Error ──────────────────────────────────────────────────────────────
  'aiError.title': 'Service unavailable',
  'aiError.subtitle': 'Enter your API key to continue.',
  'aiError.invalidKey': 'Invalid key or API unavailable',
  'aiError.saveError': 'Error saving key',
  'aiError.save': 'Save & Connect',
  'aiError.recheck': 'Recheck without new key',
  'common.hoursShort': 'h',
  'common.minutesShort': 'm',
  'app.badgeUnlocked': 'Achievement Get!',
  'app.welcomeBackFreeze': 'Welcome back, {name}. We kept your streak — freeze used.',
  'app.welcomeBackReset': 'Welcome back, {name}. Don\'t worry about the streak — let\'s start again together.',
  'app.greeting.night': 'Good night',
  'app.greeting.morning': 'Good morning',
  'app.greeting.afternoon': 'Good afternoon',
  'app.greeting.evening': 'Good evening',
  'app.greeting.intro': '{greeting}, {name}! I\'m Wispucci AI. Click me for the menu, or type something.',
  'app.flashcards.noneDue': 'You don\'t have any flashcards due right now.',
  'app.flashcards.openError': 'Could not open the review right now.',
  'app.quickStart.title': 'Quick Start',
  'app.quickStart.organize': 'Good. Start with one visible task and make today concrete. I opened your task board.',
  'app.quickStart.learn': 'Good. Pick one topic and follow one path. I opened course creation so you can start cleanly.',
  'app.quickStart.focus': 'Good. Protect one block of attention first. I opened Focus Mode so you can create momentum fast.',
  'app.firstCourse.title': 'First Course',
  'app.tutorialComplete': 'Good. Your first course is alive. Use the course path to learn, the bottom bar to ask, and the orb menu when you need another tool.',
  'app.levelUpTitle': 'Level Up!',
  'app.levelReached': 'You reached level {level}',
  'app.localWeb': 'local web',
  'app.inputPlaceholder': 'Type something for Wispucci AI...',
  'chatAction.openTasks': 'View tasks',
  'chatAction.openCourses': 'View courses',
  'chatAction.openCreator': 'Open creator',
  'chatAction.openFlashcards': 'Review flashcards',
  'chatAction.openCourse': 'Continue course',
  'chatAction.openTeacher': 'Open Teacher Mode',
  'chatAction.open': 'Open',
  'tutorial.kicker': 'Guided start',
  'tutorial.introTitle': 'First we build something real.',
  'tutorial.introDescription': 'You will name one course, answer a few quick questions, then plant it before jumping to the orb menu.',
  'tutorial.introDetail': 'Short and simple. No long tour.',
  'tutorial.introStatus': 'One course first. Menu second.',
  'tutorial.introAction': 'Start',
  'tutorial.introHelper': 'This intro is intentionally short.',
  'tutorial.step1': 'Step 1',
  'tutorial.step1TitleType': 'Click here and type a topic.',
  'tutorial.step1TitleContinue': 'Now press Continue.',
  'tutorial.step1TitleQuestions': 'Answer these quick questions.',
  'tutorial.step1TitlePlant': 'Now plant the course.',
  'tutorial.step1DescriptionType': 'Pick any real topic you want. After that the screen will scroll to the Continue button for you.',
  'tutorial.step1DescriptionContinue': 'Good. Start the quick setup questions. After you press Continue, the tutorial will follow the intake window itself.',
  'tutorial.step1DescriptionQuestions': 'Fill in these short setup questions so Wispucci can tailor the roadmap before the course starts growing.',
  'tutorial.step1DescriptionPlant': 'The setup is ready. Plant the course and the tutorial will immediately move on.',
  'tutorial.step1Detail': 'The tutorial now stays with you through the quick intake and skips the long wait.',
  'tutorial.step1DetailQuestions': 'You can tap example chips or type your own short answer.',
  'tutorial.step1StatusMoving': 'Moving to the orb step...',
  'tutorial.step1StatusContinue': 'Waiting for Continue...',
  'tutorial.step1StatusQuestions': 'Waiting for your answers...',
  'tutorial.step1StatusPlant': 'Waiting for Plant...',
  'tutorial.step1StatusTopic': 'Waiting for a topic...',
  'tutorial.step1HelperOpen': 'Open the course creator again if it closed.',
  'tutorial.step1HelperFollow': 'Follow the highlighted control.',
  'tutorial.step1ActionOpen': 'Open course creator',
  'tutorial.step2': 'Step 2',
  'tutorial.step2Title': 'Now click the orb.',
  'tutorial.step2Description': 'After you click the orb and the menu opens, the tutorial ends.',
  'tutorial.step2Detail': 'That is the whole first-run flow now.',
  'tutorial.step2StatusOpen': 'Menu opened.',
  'tutorial.step2StatusWait': 'Waiting for the orb click...',
  'tutorial.step2HelperFallback': 'If the orb is not visible enough, use the fallback button.',
  'tutorial.step2HelperDone': 'Good. The guide is done.',
  'tutorial.step2ActionOpen': 'Open orb menu',
  'creator.heroTitle': 'What do you want to learn?',
  'creator.heroSubtitle': 'Plant an idea — Wispucci AI turns it into a knowledge tree in 47 seconds.',
  'creator.familiarityPrompt': 'How much do you already know about this topic?',
  'creator.familiarity.new.label': 'New',
  'creator.familiarity.new.note': 'start from zero',
  'creator.familiarity.rusty.label': 'Rusty',
  'creator.familiarity.rusty.note': 'I saw it before',
  'creator.familiarity.comfortable.label': 'Comfortable',
  'creator.familiarity.comfortable.note': 'I know the basics',
  'creator.familiarity.strong.label': 'Strong',
  'creator.familiarity.strong.note': 'skip obvious basics',
  'creator.familiarity.unsure.label': 'Not sure',
  'creator.familiarity.unsure.note': 'deduce it for me',
  'creator.continue': 'Continue',
  'creator.preparingQuestions': 'Preparing questions...',
  'creator.intakeTitle': 'A few quick questions',
  'creator.intakeSubtitle': 'Wispucci AI will tune the roadmap before the course starts growing.',
  'creator.intakeProgressSummaryLabel': 'What the course is already optimizing for',
  'creator.intakeReadySummaryLabel': 'Current course direction',
  'creator.editTopic': '← Edit topic',
  'creator.generateCourse': 'Plant the course with Wispucci AI',
  'creator.planting': 'Planting knowledge...',
  'creator.startedTitle': 'Seed planted',
  'creator.startedSubtitle': 'The course is growing in the background.\nYou can return to your course list right now.',
  'creator.startedAction': 'Open course list',
  'creator.doneTitle': 'The tree has bloomed!',
  'creator.doneSubtitle': 'Lessons and topics\nall rooted ✓',
  'creator.explore': 'Explore the course',
  'creator.blockedTitle': 'Consolidation before the next course',
  'courseList.title': 'My Courses',
  'courseList.count': '{count} courses',
  'courseList.create': 'Plant a new course',
  'courseList.cooldownHint': 'You can create a course every 2 hours',
  'courseList.nextAvailable': 'Next available',
  'courseList.growing': 'Growing',
  'courseList.bloomed': 'Bloomed',
  'courseList.generatingHint': 'Growing in the background',
  'courseList.failedHint': 'Generation stopped before the course was ready',
  'courseList.failedStatus': 'stopped',
  'courseList.teacher': 'Try with Teacher',
  'courseList.emptyTitle': 'No courses yet',
  'courseList.emptySubtitle': 'Wispucci AI creates personalized courses',
  'courseList.emptyAction': 'Create first course',
  'games.pointsLabel': 'Game Points',
  'games.pointsSummary': '{total} total · +{today} today · 100 pts = 1 Pro Day',
  'games.redeem': 'Redeem Pro Day',
  'games.todayBest': 'Today\'s Best',
  'games.category.logic': '🧩 Logic',
  'games.category.memory': '🧠 Memory',
  'games.category.attention': '👁 Attention',
  'games.category.speed': '⚡ Speed',
  'games.desc.mathSpeed': 'Solve math problems before time runs out',
  'games.desc.memoryTiles': 'Remember and repeat tile patterns',
  'games.desc.patternMatch': 'Find the next number in the sequence',
  'games.desc.reactionTime': 'Click as fast as possible when you see the signal',
  'games.desc.wordScramble': 'Unscramble the hidden words',
  'games.desc.colorStroop': 'Name the color, not the word',
  'leaderboard.title': 'Leaderboard',
  'leaderboard.totalPoints': 'Total Points',
  'leaderboard.today': 'Today',
  'leaderboard.proDaysRedeemed': '{count} Pro Days redeemed',
  'leaderboard.redeem': 'Redeem Pro Day (100 pts)',
  'leaderboard.thisWeek': 'This week',
  'leaderboard.todayLabel': 'Today',
  'leaderboard.noGames': 'No games played',
  'leaderboard.best': 'best',
  'leaderboard.dailyHint': 'Play daily to earn points. 100 points = 1 Pro Day access.',
  'leaderboard.points': 'points',
  'daily.aiSays': 'Wispucci AI says:',
  'daily.feeling': 'How are you feeling?',
  'daily.close': 'Close',
  'daily.streak': 'Streak',
  'daily.xpToday': 'XP Today',
  'daily.tasks': 'Tasks',
  'daily.games': 'Games',
  'settings.profileLabel': 'PROFILE',
  'settings.ageGroup': 'AGE GROUP',
  'settings.ageGroupHint': 'Wispucci AI adjusts examples and critique level based on this group.',
  'settings.age.under16': 'Under 16',
  'settings.age.16to25': '16-25',
  'settings.age.25plus': '25+',
  'settings.age.unknown': 'Unknown',
  'settings.botLanguage': 'BOT LANGUAGE',
  'settings.modeLabel': 'MODE',
  'settings.mode.standard': 'Standard',
  'settings.mode.adhd': 'ADHD',
  'settings.mode.standardHint': 'Normal mode without format restrictions.',
  'settings.mode.adhdHint': 'Short, structured responses. No long text.',
  'settings.floatingOrb': 'FLOATING ORB',
  'settings.on': 'ON',
  'settings.off': 'OFF',
  'settings.orbSize': 'SIZE',
  'settings.orbSize.small': 'Small',
  'settings.orbSize.medium': 'Medium',
  'settings.orbSize.large': 'Large',
  'settings.orbEnabledHint': 'Appears when you minimize Wispucci AI.',
  'settings.orbDisabledHint': 'Orb is disabled.',
  'settings.browserMode': 'BROWSER MODE',
  'settings.browserModeHint': 'The desktop floating orb is replaced here by the in-page orb and browser UI. Overlay toggles are hidden because this build runs inside a normal tab.',
  'settings.plans': 'PLANS',
  'settings.plansHint': 'Free and Premium are clearly separated: see caps and their costs without the dev panel.',
  'settings.devTitle': 'DEVELOPER',
  'settings.devButton': 'DEV FULL ACCESS',
  'settings.devHint': 'Use this only for testing. It removes plan caps and enables skip controls for lessons and locked modules.',
  'settings.devStatus.dev': 'DEV FULL ACCESS',
  'settings.devStatus.premium': 'PREMIUM ACTIVE',
  'settings.devStatus.free': 'FREE ACTIVE',
  'settings.telemetry': 'TELEMETRY',
  'settings.averageShort': 'avg',
  'settings.requestsShort': 'req',
  'settings.dangerZone': 'DANGER ZONE',
  'settings.dangerZoneHint': 'Start from zero. This deletes your local profile, onboarding state, tasks, chats, courses, flashcards, memories, streak, XP, and game progress.',
  'settings.resetButton': 'DELETE PROFILE AND START OVER',
  'settings.resetting': 'RESETTING PROFILE...',
  'settings.versionPrivate': 'private',
  'settings.confirmReset': 'Delete your profile and all local progress? This will remove tasks, chat history, courses, flashcards, memories, game progress, streak, XP, and return the app to onboarding.',
  'settings.resetError': 'Could not reset the profile right now. Try again.',
  'settings.tier.freeNote': 'Compact and affordable: roughly a third of premium depth',
  'settings.tier.premiumNote': 'Deeper and more powerful: roughly 3x space and depth',
  'sidebar.todoCount': '{count} to do',
  'sidebar.doneCount': '{count} done',
  'sidebar.emptyHint': 'Tell AURA what you need to do',
  'sidebar.streakDays': '{count} day streak',
  'sidebar.streak.start': "Let's get started!",
  'sidebar.streak.keepUp': 'Keep it up!',
  'sidebar.streak.onFire': "You're on fire!",
  'sidebar.streak.legendary': 'Legendary!',
  'sidebar.streak.master': 'ABSOLUTE MASTER!',
  'sidebar.badges': 'Badges',
  'sidebar.achievements': 'Achievements',
  'sidebar.nextLevelCourses': 'Next level at {count} courses',
  'sidebar.nextLevelWords': 'Next level at {count} words',
  'sidebar.nextLevelMinutes': 'Next level at {count} minutes',
  'sidebar.adhdModeActive': 'ADHD mode active',
  'sidebar.quickToggle': 'Ctrl+Shift+A - quick toggle',
  'errorBoundary.title': 'Something went wrong',
  'errorBoundary.retry': 'Try again',
  'errorBoundary.unknown': 'Unknown error',
  'game.score': 'Score: {score}',
  'game.pointsAward': '+{points} points',
  'game.backToGames': 'Back to Games',
  'game.correctCount': '{count} correct',
  'game.roundsCorrect': '{correct}/{total} rounds correct',
  'game.answeredCount': '{answered}/{total} answered',
  'game.averageMs': 'Average: {ms}ms',
  'game.roundProgress': 'Round {current}/{total}',
  'game.quit': 'Quit',
  'game.timeShort': '{seconds}s',
  'game.math.success': 'Great job!',
  'game.math.fail': 'Game Over',
  'game.memory.complete': 'Memory Complete!',
  'game.memory.memorize': 'Memorize the tiles!',
  'game.memory.tapRemember': 'Tap the tiles you remember',
  'game.memory.submit': 'Submit ({count} selected)',
  'game.reaction.complete': 'Reaction Complete!',
  'game.reaction.wait': 'Wait...',
  'game.reaction.tap': 'TAP!',
  'game.reaction.tooEarly': 'Too early!',
  'game.reaction.waitGreen': 'Wait for the green signal...',
  'game.reaction.clickNow': 'Click NOW!',
  'game.reaction.waitNext': 'Wait for the signal next time',
  'game.reaction.feedbackAmazing': 'Amazing!',
  'game.reaction.feedbackGood': 'Good!',
  'game.reaction.feedbackKeepTrying': 'Keep trying!',
  'game.word.complete': 'Words Complete!',
  'game.word.unscramble': 'Unscramble the word',
  'game.word.answerPlaceholder': 'Your answer...',
  'game.word.skip': 'Skip word',
  'game.pattern.complete': 'Pattern Complete!',
  'game.pattern.prompt': 'What comes next in the sequence?',
  'game.stroop.complete': 'Stroop Complete!',
  'game.stroop.question': 'What COLOR is the text displayed in?',
  'game.stroop.ignore': '(ignore what the word says)',
  'lessonQuiz.blockedStart': 'Cannot start the quiz for this lesson right now.',
  'lessonQuiz.loading': 'GENERATING QUIZ...',
  'lessonQuiz.passedTitle': 'QUIZ PASSED!',
  'lessonQuiz.passedBody1': 'YOU PASSED THE RECALL TEST. JUST A SHORT PRACTICE LEFT TO CLOSE THE LESSON.',
  'lessonQuiz.passedBody2': 'THE QUIZ CHECKS IF YOU RECOGNIZE. PRACTICE CHECKS IF YOU CAN USE IT.',
  'lessonQuiz.afterPractice': 'AFTER PRACTICE',
  'lessonQuiz.enterPractice': 'ENTER PRACTICE',
  'lessonQuiz.failedTitle': 'REVIEW NEEDED!',
  'lessonQuiz.failedBody': 'YOU GOT {count} {label} WRONG. FIX YOUR RECALL FIRST, THEN YOU\'LL REACH PRACTICE.',
  'lessonQuiz.failedBody2': 'AFTER RE-READING THE LESSON, THE NEXT ATTEMPT WILL PREPARE A NEW SHORT SET OF QUESTIONS.',
  'lessonQuiz.questionSingular': 'QUESTION',
  'lessonQuiz.questionPlural': 'QUESTIONS',
  'lessonQuiz.rereadLesson': 'RE-READ LESSON',
  'lessonQuiz.backToModule': 'BACK TO MODULE',
  'lessonQuiz.backToLesson': 'BACK TO LESSON',
  'lessonQuiz.blockedTitle': 'QUIZ TEMPORARILY BLOCKED',
  'lessonQuiz.correct': 'CORRECT!',
  'lessonQuiz.seeResult': 'SEE RESULT',
  'lessonQuiz.next': 'NEXT',
  'lessonQuiz.wrong': 'WRONG!',
  'lessonQuiz.correctAnswer': 'CORRECT ANSWER:',
  'lessonQuiz.reminder': 'REMINDER',
  'lessonQuiz.hintFallback': 'Re-read the lesson carefully — the answer is in the lesson content.',
  'lessonQuiz.continueQuiz': 'CONTINUE QUIZ',
  'lessonQuiz.header': 'QUIZ · LESSON {num}',
  'lessonQuiz.answerPlaceholder': 'Type your answer...',
  'lessonQuiz.checkAnswer': 'CHECK ANSWER',
  'lessonQuiz.back': '← BACK',
}
