import type { StringCatalog } from '../i18n'

export const strings: StringCatalog = {
  // ─── Onboarding ────────────────────────────────────────────────────────────
  'onboarding.hello': 'Bună! Sunt Wispucci AI.',
  'onboarding.subtitle': 'Asistentul tău personal pentru focus și progres.\nTotul rulează local — nimeni nu vede conversațiile noastre.',
  'onboarding.namePlaceholder': 'Cum te cheamă?',
  'onboarding.continue': 'Continuă',
  'onboarding.importantQuestion': '{name}, o întrebare importantă.',
  'onboarding.adhdQuestion': 'Ai ADHD sau probleme cu motivația/focusul?',
  'onboarding.adhdHint': 'Asta mă ajută să fiu mai blând și adaptiv cu tine.',
  'onboarding.adhdYes': 'Da, am nevoie de modul empatic',
  'onboarding.adhdNo': 'Nu, sunt ok cu modul normal',
  'onboarding.languageTitle': 'Limba preferată?',
  'onboarding.languageHint': 'Wispucci AI va răspunde în limba aleasă',
  'onboarding.start': 'Hai să începem!',
  'onboarding.defaultReward1': 'Muzica preferată 🎵',
  'onboarding.defaultReward2': '5 min pauză ☕',
  'onboarding.defaultReward3': 'Meme amuzant 😂',

  // ─── Energy Prompt ──────────────────────────────────────────────────────────
  'energy.greeting': 'Bună dimineața, {name}!',
  'energy.question': 'Cum e nivelul tău de energie azi?',
  'energy.confirm': 'Confirmă ({level}/10)',
  'energy.skip': 'Sari peste',
  'energy.1': 'Foarte rău',
  'energy.2': 'Rău',
  'energy.3': 'Slab',
  'energy.4': 'Meh',
  'energy.5': 'Ok',
  'energy.6': 'Decent',
  'energy.7': 'Bine',
  'energy.8': 'Foarte bine',
  'energy.9': 'Excelent',
  'energy.10': 'MAXIM!',

  // ─── Greetings (time of day) ───────────────────────────────────────────────
  'greeting.night': 'Noapte bună, {name}.',
  'greeting.morning': 'Bună dimineața, {name}.',
  'greeting.afternoon': 'Bună ziua, {name}.',
  'greeting.evening': 'Bună seara, {name}.',

  // ─── Floating Menu ─────────────────────────────────────────────────────────
  'menu.tasks': 'Taskuri',
  'menu.games': 'Jocuri',
  'menu.focus': 'Focus',
  'menu.teacher': 'Profesor',
  'menu.memory': 'Memorie',
  'menu.achievements': 'Realizări',
  'menu.settings': 'Setări',
  'menu.friends': 'Prieteni',

  // ─── Sidebar ───────────────────────────────────────────────────────────────
  'sidebar.tasks': 'Taskuri',
  'sidebar.stats': 'Stats',
  'sidebar.newTask': 'Task nou...',
  'sidebar.noTasks': 'Niciun task încă. Adaugă unul!',

  // ─── Chat ──────────────────────────────────────────────────────────────────
  'chat.placeholder': 'Scrie un mesaj...',
  'chat.welcome': 'Salut, sunt Wispucci AI — asistentul tău personal de focus. Întreabă-mă orice, trimite-mi cod, sau spune-mi cum te simți azi.',
  'chat.thinking': 'Gândesc...',
  'chat.error': 'Ceva nu a mers bine. Încearcă din nou.',
  'chat.limitReached': 'Limita de mesaje pe azi s-a atins. Revino mâine sau fă upgrade la Premium pentru chat nelimitat.',

  // ─── Course Creator ────────────────────────────────────────────────────────
  'creator.title': 'Creează un curs',
  'creator.placeholder': 'Ce vrei să înveți?',
  'creator.generate': 'Generează',
  'creator.generating': 'Se generează...',
  'creator.done': 'Curs creat!',
  'creator.goToCourse': 'Du-te la curs',
  'creator.blocked': 'Nu am putut genera cursul acum.',
  'creator.back': '← Înapoi',

  // ─── Course View ───────────────────────────────────────────────────────────
  'course.modules': 'Module',
  'course.lessons': 'Lecții',
  'course.completed': 'Completat',
  'course.locked': 'Blocat',
  'course.startLesson': 'Începe lecția',
  'course.continueLesson': 'Continuă',
  'course.back': '← Înapoi la cursuri',
  'course.noContent': 'Niciun conținut încă.',

  // ─── Lesson Viewer / Quiz ──────────────────────────────────────────────────
  'lesson.loading': 'Se pregătește lecția...',
  'lesson.readConfirm': 'AM CITIT',
  'lesson.startTest': 'Începe testul',
  'lesson.quiz.correct': 'Corect!',
  'lesson.quiz.wrong': 'Nu chiar.',
  'lesson.quiz.next': 'Următorul',
  'lesson.quiz.finish': 'Termină',
  'lesson.quiz.score': 'Scor: {score}/{total}',

  // ─── Teacher Mode ──────────────────────────────────────────────────────────
  'teacher.preparing': 'Încă pregătesc explicația profesorului...',
  'teacher.readConfirm': 'Am citit — începe testul',
  'teacher.limitNotice': 'Limită atinsă',
  'teacher.back': '← Înapoi',

  // ─── Lesson Support Panel ──────────────────────────────────────────────────
  'support.howWell': 'Cât de bine ai înțeles?',
  'support.score': '{score}/10',
  'support.clarify': 'Pune o întrebare',
  'support.clarifyPlaceholder': 'Ce nu a fost clar?',
  'support.flashcards': 'Flashcarduri',
  'support.continueTest': 'Continuă la test',
  'support.startTest': 'Începe testul',
  'support.needScore7': 'Ai nevoie de minim 7/10 pentru a continua.',
  'support.recallTitle': 'Recall rapid',

  // ─── Flashcards ────────────────────────────────────────────────────────────
  'flashcard.noCards': 'Niciun flashcard',
  'flashcard.back': '← Înapoi',
  'flashcard.tap': 'Apasă pentru a vedea',
  'flashcard.easy': 'Ușor ✅',
  'flashcard.medium': 'Mediu 🤔',
  'flashcard.hard': 'Nu am știut 😅',
  'flashcard.done': 'Sesiune completă!',
  'flashcard.accuracy': '{percent}% acuratețe',

  // ─── Achievements ──────────────────────────────────────────────────────────
  'achievements.title': 'Realizări',
  'achievements.subtitle': 'Vezi progresul exact până la următorul unlock',
  'achievements.level': 'Nivel {level}',
  'achievements.levelLabel': 'NIVEL',
  'achievements.xp': '{xp} XP',
  'achievements.streak': '{days} zile la rând',
  'achievements.lessons': '{count} lecții',
  'achievements.courses': '{count} cursuri',
  'achievements.words': '{count} cuvinte',
  'achievements.time': '{minutes} min',
  'achievements.nextMilestone': 'Următorul: {target}',
  'achievements.lessonsTrack': 'LECȚII',
  'achievements.lessonsUnit': 'lecții',
  'achievements.lessonsLeft': 'Mai ai {count} lecții până la next milestone',
  'achievements.milestoneHit': 'Milestone atins. Următorul vine în {size} lecții.',
  'achievements.coursesTrack': 'CURSURI',
  'achievements.coursesUnit': 'cursuri',
  'achievements.coursesLeft': 'Mai ai {count} cursuri până la următorul achievement',
  'achievements.wordsTrack': 'CUVINTE',
  'achievements.wordsUnit': 'cuvinte',
  'achievements.wordsLeft': 'Mai ai {count} cuvinte până la următorul achievement',
  'achievements.timeTrack': 'TIMP',
  'achievements.timeUnit': 'minute',
  'achievements.timeLeft': 'Mai ai {count} minute până la următorul achievement',
  'achievements.allUnlocked': 'Toate achievements deblocate',
  'achievements.totalBadges': 'Total badges deblocate: {count}',
  'achievements.bonusXP': 'Bonus XP strâns: {xp}',

  // ─── Settings ──────────────────────────────────────────────────────────────
  'settings.title': 'Setări',
  'settings.plan': 'Plan',
  'settings.activeWindow': 'Fereastră activă',
  'settings.coursesPerMonth': 'CURSURI / LUNĂ',
  'settings.coursesPer2h': 'CURSURI / 2H',
  'settings.chatPerDay': 'CHAT / ZI',
  'settings.lessonsPer2h': 'LECȚII / 2H',
  'settings.lessonsPerMonth': 'LECȚII / LUNĂ',
  'settings.flashcards': 'FLASHCARDURI',
  'settings.pdfExport': 'EXPORT PDF',
  'settings.yes': 'DA',
  'settings.no': 'NU',
  'settings.unlimited': '∞',
  'settings.active': 'ACTIV',
  'settings.planLabel': 'PLAN',
  'settings.tokenSources': 'SURSE CONSUM TOKENI',
  'settings.psychFrame': 'ÎNCADRARE PSIHOLOGICĂ',
  'settings.noTraffic': 'Nu e suficient trafic AI pentru comparație momentan.',
  'settings.clearChat': 'Șterge istoricul chat-ului',
  'settings.clearConfirm': 'Șters!',
  'settings.language': 'Limbă',
  'settings.tier.free': 'Gratuit',
  'settings.tier.premium': 'Premium',

  // ─── Top Indicator ─────────────────────────────────────────────────────────
  'indicator.chatExhausted': 'CHAT AI EPUIZAT',
  'indicator.chatRemaining': 'CHAT AI {remaining} / {limit} RĂMAȘI',
  'indicator.messagesLeft': '{count} mesaje rămase azi',
  'indicator.messagesExhausted': 'CHAT EPUIZAT · se resetează mâine',
  'indicator.lessonMilestoneHit': 'Milestone mic atins',
  'indicator.lessonsUntilMilestone': '{count} lecții până la next milestone',

  // ─── Focus Mode ────────────────────────────────────────────────────────────
  'focus.deepWork': 'Deep Work',
  'focus.sprint': 'Sprint',
  'focus.flow': 'Flow',
  'focus.custom': 'Custom',
  'focus.start': 'Start',
  'focus.pause': 'Pauză',
  'focus.resume': 'Continuă',
  'focus.stop': 'Stop',
  'focus.sessionComplete': 'Sesiune completă!',
  'focus.back': '← Înapoi',

  // ─── Pomodoro ──────────────────────────────────────────────────────────────
  'pomodoro.work': 'Timp de focus',
  'pomodoro.break': 'Pauză',
  'pomodoro.sessions': '{count} sesiuni',
  'pomodoro.wellDone': 'Bravo! Ia o pauză.',
  'pomodoro.breakOver': 'Pauza s-a terminat. Hai mai departe!',
  'pomodoro.focusActivated': 'Modul focus activat. La treabă!',
  'pomodoro.breakStarted': 'Pauza a început.',
  'pomodoro.back': '← Înapoi',

  // ─── Body Doubling ─────────────────────────────────────────────────────────
  'companion.together': 'împreună',
  'companion.exit': '← ieși',
  'companion.main': 'Suntem împreună, {name}.',
  'companion.mainNoName': 'Suntem împreună.',
  'companion.sub': 'Lucrează în liniște. Sunt aici.',
  'companion.phrases.0': 'Sunt aici',
  'companion.phrases.1': 'Te descurci bine',
  'companion.phrases.2': 'Respiră',
  'companion.phrases.3': 'Nu ești singur',
  'companion.phrases.4': 'Ia o pauză dacă ai nevoie',
  'companion.phrases.5': 'Ești pe drumul bun',
  'companion.phrases.6': 'Tot ce faci contează',
  'companion.phrases.7': 'Sunt fix aici',
  'companion.phrases.8': 'Mă gândesc la tine',
  'companion.phrases.9': 'Ia-o ușurel',

  // ─── Dopamine Menu ─────────────────────────────────────────────────────────
  'dopamine.youtube': '15 min YouTube',
  'dopamine.game': '20 min gaming',
  'dopamine.walk': 'Plimbare afară',
  'dopamine.snack': 'Snack preferat',
  'dopamine.music': 'Ascultă muzică',
  'dopamine.social': '10 min social media',
  'dopamine.nap': '20 min power nap',
  'dopamine.draw': 'Desenează ceva',
  'dopamine.stretch': 'Stretching / Yoga',
  'dopamine.chat': 'Vorbește cu cineva',
  'dopamine.coffee': 'Pauză de cafea',
  'dopamine.custom': 'Recompensă custom',
  'dopamine.enjoy': 'Bucură-te!',
  'dopamine.deserved': 'Ai meritat-o. Relaxează-te.',
  'dopamine.backToWork': 'Înapoi la treabă',
  'dopamine.congrats': 'Felicitări!',

  // ─── Career Mirror ─────────────────────────────────────────────────────────
  'career.title': 'Oglinda carierei',
  'career.loading': 'Generez proiecția...',
  'career.back': '← Înapoi',

  // ─── Daily Summary ─────────────────────────────────────────────────────────
  'daily.title': 'Rezumatul zilei',
  'daily.loading': 'Generez rezumatul...',
  'daily.back': '← Înapoi',

  // ─── Brain Games ───────────────────────────────────────────────────────────
  'games.title': 'Jocuri pentru creier',
  'games.back': '← Înapoi',
  'games.mathSpeed': 'Viteză la mate',
  'games.memoryTiles': 'Tile-uri memorie',
  'games.patternMatch': 'Potrivire pattern',
  'games.reactionTime': 'Timp de reacție',
  'games.wordScramble': 'Cuvinte amestecate',
  'games.colorStroop': 'Stroop Culori',
  'games.todayPoints': 'Azi',
  'games.totalPoints': 'Total',
  'games.leaderboard': 'Clasament',
  'games.difficulty': 'Dificultate',

  // ─── Memory Panel ──────────────────────────────────────────────────────────
  'memory.stable': 'Stabile',
  'memory.stableHint': 'Fapte care rămân (cine ești, ce iubești, obiective)',
  'memory.moments': 'Momente',
  'memory.momentsHint': 'Momente marcate emoțional (victorii, lupte, descoperiri)',
  'memory.session': 'Sesiune',
  'memory.sessionHint': 'Context din sesiunea curentă (expiră în 6h dacă nu e important)',
  'memory.all': 'Toate',
  'memory.add': '+ Adaugă',
  'memory.addNew': 'Adaugă',
  'memory.remember': 'Reține',
  'memory.placeholder': 'Ex: Lucrez cel mai bine dimineața · Vreau să termin cartea până luni · Mă stresează deadline-urile mari',
  'memory.title': 'Memoria noastră',
  'memory.subtitle': 'Aici vezi tot ce îmi amintesc despre tine. Nu e un secret — e al tău. Poți șterge orice, oricând.',
  'memory.tagline': 'ceea ce rețin',
  'memory.empty': 'Nicio amintire încă.',

  // ─── Levels ────────────────────────────────────────────────────────────────
  'level.1': 'Începător',
  'level.2': 'Curios',
  'level.3': 'Constant',
  'level.4': 'Focusat',
  'level.5': 'Dedicat',
  'level.6': 'Performer',
  'level.7': 'Expert',
  'level.8': 'Maestru',

  // ─── Badges ────────────────────────────────────────────────────────────────
  'badge.first_session': 'Prima sesiune',
  'badge.streak_3': '3 zile la rând',
  'badge.streak_7': '7 zile de foc',
  'badge.streak_30': '30 zile legendar',
  'badge.level_3': 'Nivel 3 atins',
  'badge.level_5': 'Nivel 5 atins',
  'badge.xp_500': '500 XP',
  'badge.xp_1000': '1000 XP',
  'badge.first_course': 'Primul curs început',
  'badge.course_complete': 'Un curs completat',
  'badge.course_1': '1 curs completat',
  'badge.course_3': '3 cursuri completate',
  'badge.course_5': '5 cursuri completate',
  'badge.course_10': '10 cursuri completate',
  'badge.words_200': '200 cuvinte',
  'badge.words_1000': '1000 cuvinte',
  'badge.words_5000': '5000 cuvinte',
  'badge.words_15000': '15000 cuvinte',
  'badge.time_30': '30 minute în app',
  'badge.time_120': '2 ore în app',
  'badge.time_600': '10 ore în app',
  'badge.time_1800': '30 ore în app',

  // ─── Moods ─────────────────────────────────────────────────────────────────
  'mood.happy': 'Fericit',
  'mood.excited': 'Entuziasmat',
  'mood.think': 'Gânditor',
  'mood.sleepy': 'Somnoros',
  'mood.sad': 'Trist',
  'mood.love': 'Recunoscător',
  'mood.focus': 'Focusat',

  // ─── Crisis ────────────────────────────────────────────────────────────────
  'crisis.response': `Înțeleg că treci printr-un moment foarte greu. Nu ești singur/singură în asta.

Te rog sună ACUM la unul din aceste numere — oameni pregătiți te ascultă, gratuit, 24/7:
• Telefonul Sufletului: 0800 801 200
• Pentru copii/tineri: 116 111
• Internațional: findahelpline.com

Nu trebuie să treci singur/singură prin asta. Acești oameni sunt antrenați să ajute.`,

  // ─── Tier Limit Messages ───────────────────────────────────────────────────
  'limits.courseWindow': '🧠 CONSOLIDARE ACTIVĂ\n\nAi creat deja {limit} cursuri în ultimele 2 ore pe planul {label}. Pauză — lasă cursurile existente să se așeze.\n\nRevino peste {reset} sau continuă un curs deja început.',
  'limits.courseMonth': '📚 LIMITĂ LUNARĂ DE CURSURI\n\nAi atins limita lunară de {limit} cursuri pe planul {label}.\n\nPoți continua cursurile existente și primești sloturi noi luna viitoare.',
  'limits.lessonWindow': '📚 PAUZĂ DE CONSOLIDARE\n\nAi deschis deja {limit} lecții noi în ultimele 2 ore pe planul {label}. Continuă ce ai început și revino după reset.\n\nSlotul următor se deschide în {reset}.',
  'limits.lessonMonth': '🧩 LIMITĂ LUNARĂ DE LECȚII\n\nAi atins limita lunară de {limit} lecții pe planul {label}.\n\nPoți continua lecțiile existente și primești sloturi noi luna viitoare.',
  'limits.chatBudget': '💬 LIMITA DE CHAT ATINSĂ\n\nAi folosit toate cele {limit} mesaje zilnice pe planul {label}.\n\nMesajele se resetează mâine. Fă upgrade la Premium pentru chat nelimitat.',
  'limits.chatExhausted': 'CHAT EPUIZAT · se resetează mâine',

  // ─── Tier Notes ────────────────────────────────────────────────────────────
  'tierNote.courses': 'Cursurile au două garduri: un cap de ritm per 2 ore și un cap de volum pe lună. Primul oprește spam-ul impulsiv, al doilea menține economia sub control.',
  'tierNote.chat': 'Chat-ul este singurul buget AI blocant. Cursurile și lecțiile folosesc telemetria pentru cost, nu blocaje de tokeni.',
  'tierNote.lessons': 'Lecțiile au atât un cap de 2 ore cât și un cap lunar. Re-intrarea în aceeași lecție nu consumă un slot nou.',
  'tierNote.flashcardsUnlimited': 'Acest plan nu limitează numărul total de flashcard-uri.',
  'tierNote.flashcardsLimited': 'Limita de flashcard-uri menține sistemul dens și repetabil, nu un depozit de carduri uitate.',
  'tierNote.pdfExportYes': 'Exportul PDF rămâne activ când suprafața de export e deschisă în UI.',
  'tierNote.pdfExportNo': 'Exportul PDF e blocat pe acest plan ca feature de confort, nu ca feature esențial de învățare.',

  // ─── Overlay / Tray ────────────────────────────────────────────────────────
  'overlay.newLesson': 'Hai să învățăm ceva nou!',
  'overlay.progress': 'Progresul se face pas cu pas.',
  'overlay.youGotThis': 'Poți!',
  'overlay.keepGoing': 'Continuă!',
  'tray.show': 'Arată Wispucci AI',
  'tray.quit': 'Ieșire',

  // ─── Game colors (Stroop) ──────────────────────────────────────────────────
  'color.red': 'ROȘU',
  'color.blue': 'ALBASTRU',
  'color.green': 'VERDE',
  'color.yellow': 'GALBEN',
  'color.orange': 'PORTOCALIU',

  // ─── Themes ────────────────────────────────────────────────────────────────
  'theme.forest': 'Pădure',

  // ─── Common ────────────────────────────────────────────────────────────────
  'common.back': '← Înapoi',
  'common.close': 'Închide',
  'common.save': 'Salvează',
  'common.cancel': 'Anulează',
  'common.loading': 'Se încarcă...',
  'common.noData': 'Niciun dat încă.',

  // ─── AI Error ──────────────────────────────────────────────────────────────
  'aiError.title': 'Serviciu indisponibil',
  'aiError.subtitle': 'Introdu cheia API pentru a continua.',
  'aiError.invalidKey': 'Cheie invalidă sau API indisponibil',
  'aiError.saveError': 'Eroare la salvare',
  'aiError.save': 'Salvează & Conectează',
  'aiError.recheck': 'Recheck fără cheie nouă',
  'common.hoursShort': 'h',
  'common.minutesShort': 'm',
  'app.badgeUnlocked': 'Realizare deblocată!',
  'app.welcomeBackFreeze': 'Bine ai revenit, {name}. Ți-am păstrat streak-ul — freeze folosit.',
  'app.welcomeBackReset': 'Bine ai revenit, {name}. Nu-ți face griji pentru streak — începem din nou împreună.',
  'app.greeting.night': 'Noapte bună',
  'app.greeting.morning': 'Bună dimineața',
  'app.greeting.afternoon': 'Bună ziua',
  'app.greeting.evening': 'Bună seara',
  'app.greeting.intro': '{greeting}, {name}! Sunt Wispucci AI. Apasă pe mine pentru meniu sau scrie ceva.',
  'app.flashcards.noneDue': 'Nu ai flashcard-uri scadente acum.',
  'app.flashcards.openError': 'Nu am putut deschide recapitularea acum.',
  'app.quickStart.title': 'Pornire rapidă',
  'app.quickStart.organize': 'Bine. Începe cu o singură sarcină vizibilă și fă ziua concretă. Am deschis panoul de task-uri.',
  'app.quickStart.learn': 'Bine. Alege un singur subiect și urmează o singură cale. Am deschis creatorul de curs ca să începi curat.',
  'app.quickStart.focus': 'Bine. Protejează mai întâi un bloc de atenție. Am deschis Focus Mode ca să prinzi rapid momentum.',
  'app.firstCourse.title': 'Primul curs',
  'app.tutorialComplete': 'Bine. Primul tău curs e viu. Folosește traseul cursului ca să înveți, bara de jos ca să întrebi și meniul orbului când ai nevoie de alt instrument.',
  'app.levelUpTitle': 'Level Up!',
  'app.levelReached': 'Ai ajuns la nivelul {level}',
  'app.localWeb': 'local web',
  'app.inputPlaceholder': 'Scrie ceva pentru Wispucci AI...',
  'chatAction.openTasks': 'Vezi task-urile',
  'chatAction.openCourses': 'Vezi cursurile',
  'chatAction.openCreator': 'Deschide creatorul',
  'chatAction.openFlashcards': 'Recapitulează flashcard-urile',
  'chatAction.openCourse': 'Continuă cursul',
  'chatAction.openTeacher': 'Deschide Teacher Mode',
  'chatAction.open': 'Deschide',
  'tutorial.kicker': 'Pornire ghidată',
  'tutorial.introTitle': 'Mai întâi construim ceva real.',
  'tutorial.introDescription': 'Vei numi un curs, vei răspunde la câteva întrebări rapide, apoi îl vei planta înainte să sari în meniul orbului.',
  'tutorial.introDetail': 'Scurt și simplu. Fără tur lung.',
  'tutorial.introStatus': 'Mai întâi cursul. Apoi meniul.',
  'tutorial.introAction': 'Începe',
  'tutorial.introHelper': 'Introducerea asta e intenționat scurtă.',
  'tutorial.step1': 'Pasul 1',
  'tutorial.step1TitleType': 'Apasă aici și scrie un subiect.',
  'tutorial.step1TitleContinue': 'Acum apasă „Continuă”.',
  'tutorial.step1TitleQuestions': 'Răspunde la aceste întrebări rapide.',
  'tutorial.step1TitlePlant': 'Acum plantează cursul.',
  'tutorial.step1DescriptionType': 'Alege orice subiect real vrei. După asta, ecranul va derula singur la butonul „Continuă”.',
  'tutorial.step1DescriptionContinue': 'Bine. Pornește etapa scurtă de ajustare. După „Continuă”, tutorialul va urmări chiar fereastra cu întrebări.',
  'tutorial.step1DescriptionQuestions': 'Completează aceste întrebări scurte ca Wispucci să adapteze roadmap-ul înainte să înceapă generarea cursului.',
  'tutorial.step1DescriptionPlant': 'Configurarea este gata. Plantează cursul și tutorialul merge imediat mai departe.',
  'tutorial.step1Detail': 'Tutorialul rămâne acum cu tine în etapa scurtă de intake și sare peste așteptarea lungă.',
  'tutorial.step1DetailQuestions': 'Poți apăsa pe exemplele rapide sau poți scrie propriul răspuns scurt.',
  'tutorial.step1StatusMoving': 'Trecem la pasul cu orbul...',
  'tutorial.step1StatusContinue': 'Aștept „Continuă”...',
  'tutorial.step1StatusQuestions': 'Aștept răspunsurile...',
  'tutorial.step1StatusPlant': 'Aștept pornirea cursului...',
  'tutorial.step1StatusTopic': 'Aștept un subiect...',
  'tutorial.step1HelperOpen': 'Deschide din nou creatorul de curs dacă s-a închis.',
  'tutorial.step1HelperFollow': 'Urmează controlul evidențiat.',
  'tutorial.step1ActionOpen': 'Deschide creatorul de curs',
  'tutorial.step2': 'Pasul 2',
  'tutorial.step2Title': 'Acum apasă pe orb.',
  'tutorial.step2Description': 'După ce apeși pe orb și se deschide meniul, tutorialul se termină.',
  'tutorial.step2Detail': 'Acesta este acum tot fluxul de primă pornire.',
  'tutorial.step2StatusOpen': 'Meniu deschis.',
  'tutorial.step2StatusWait': 'Aștept click pe orb...',
  'tutorial.step2HelperFallback': 'Dacă orbul nu este suficient de vizibil, folosește butonul de rezervă.',
  'tutorial.step2HelperDone': 'Bine. Ghidul s-a terminat.',
  'tutorial.step2ActionOpen': 'Deschide meniul orbului',
  'creator.heroTitle': 'Ce vrei să înveți?',
  'creator.heroSubtitle': 'Plantează o idee — Wispucci AI o transformă într-un arbore de cunoaștere în 47 de secunde.',
  'creator.familiarityPrompt': 'Cât de bine cunoști deja acest subiect?',
  'creator.familiarity.new.label': 'Nou',
  'creator.familiarity.new.note': 'pornește de la zero',
  'creator.familiarity.rusty.label': 'Ruginit',
  'creator.familiarity.rusty.note': 'am mai văzut asta',
  'creator.familiarity.comfortable.label': 'Confortabil',
  'creator.familiarity.comfortable.note': 'știu bazele',
  'creator.familiarity.strong.label': 'Puternic',
  'creator.familiarity.strong.note': 'sari peste bazele evidente',
  'creator.familiarity.unsure.label': 'Nu sunt sigur',
  'creator.familiarity.unsure.note': 'deduce pentru mine',
  'creator.continue': 'Continuă',
  'creator.preparingQuestions': 'Pregătesc întrebările...',
  'creator.intakeTitle': 'Câteva întrebări rapide',
  'creator.intakeSubtitle': 'Wispucci AI va ajusta roadmap-ul înainte ca acest curs să înceapă să crească.',
  'creator.intakeProgressSummaryLabel': 'La ce se optimizează deja cursul',
  'creator.intakeReadySummaryLabel': 'Direcția actuală a cursului',
  'creator.editTopic': '← Editează subiectul',
  'creator.generateCourse': 'Plantează cursul cu Wispucci AI',
  'creator.planting': 'Plantăm cunoaștere...',
  'creator.startedTitle': 'Sămânța a fost plantată',
  'creator.startedSubtitle': 'Cursul crește în fundal.\nPoți reveni acum la lista de cursuri.',
  'creator.startedAction': 'Deschide lista de cursuri',
  'creator.doneTitle': 'Arborele a înflorit!',
  'creator.doneSubtitle': 'Lecțiile și temele\nsunt deja înrădăcinate ✓',
  'creator.explore': 'Explorează cursul',
  'creator.blockedTitle': 'Consolidare înainte de următorul curs',
  'courseList.title': 'Cursurile mele',
  'courseList.count': '{count} cursuri',
  'courseList.create': 'Plantează un curs nou',
  'courseList.cooldownHint': 'Poți crea un curs la fiecare 2 ore',
  'courseList.nextAvailable': 'Disponibil din nou',
  'courseList.growing': 'În creștere',
  'courseList.bloomed': 'Înflorit',
  'courseList.generatingHint': 'Crește în fundal',
  'courseList.failedHint': 'Generarea s-a oprit înainte ca cursul să fie gata',
  'courseList.failedStatus': 'oprit',
  'courseList.teacher': 'Încearcă cu profesorul',
  'courseList.emptyTitle': 'Nu există cursuri încă',
  'courseList.emptySubtitle': 'Wispucci AI creează cursuri personalizate',
  'courseList.emptyAction': 'Creează primul curs',
  'games.pointsLabel': 'Puncte de joc',
  'games.pointsSummary': '{total} total · +{today} azi · 100 pct = 1 Pro Day',
  'games.redeem': 'Redeem Pro Day',
  'games.todayBest': 'Cel mai bun azi',
  'games.category.logic': '🧩 Logică',
  'games.category.memory': '🧠 Memorie',
  'games.category.attention': '👁 Atenție',
  'games.category.speed': '⚡ Viteză',
  'games.desc.mathSpeed': 'Rezolvă calculele înainte să expire timpul',
  'games.desc.memoryTiles': 'Memorează și repetă modele de tile-uri',
  'games.desc.patternMatch': 'Găsește următorul număr din secvență',
  'games.desc.reactionTime': 'Apasă cât poți de repede când vezi semnalul',
  'games.desc.wordScramble': 'Descâlcește cuvintele ascunse',
  'games.desc.colorStroop': 'Spune culoarea, nu cuvântul',
  'leaderboard.title': 'Clasament',
  'leaderboard.totalPoints': 'Puncte totale',
  'leaderboard.today': 'Azi',
  'leaderboard.proDaysRedeemed': '{count} Pro Days redeem-uite',
  'leaderboard.redeem': 'Redeem Pro Day (100 pct)',
  'leaderboard.thisWeek': 'Săptămâna aceasta',
  'leaderboard.todayLabel': 'Azi',
  'leaderboard.noGames': 'Niciun joc jucat',
  'leaderboard.best': 'best',
  'leaderboard.dailyHint': 'Joacă zilnic ca să câștigi puncte. 100 puncte = 1 zi Pro.',
  'leaderboard.points': 'puncte',
  'daily.aiSays': 'Wispucci AI spune:',
  'daily.feeling': 'Cum te simți?',
  'daily.close': 'Închide',
  'daily.streak': 'Streak',
  'daily.xpToday': 'XP azi',
  'daily.tasks': 'Task-uri',
  'daily.games': 'Jocuri',
  'settings.profileLabel': 'PROFIL',
  'settings.ageGroup': 'GRUPĂ DE VÂRSTĂ',
  'settings.ageGroupHint': 'Wispucci AI adaptează exemplele și nivelul de critică după această grupă.',
  'settings.age.under16': 'Sub 16',
  'settings.age.16to25': '16-25',
  'settings.age.25plus': '25+',
  'settings.age.unknown': 'Necunoscut',
  'settings.botLanguage': 'LIMBA BOTULUI',
  'settings.modeLabel': 'MOD',
  'settings.mode.standard': 'Standard',
  'settings.mode.adhd': 'ADHD',
  'settings.mode.standardHint': 'Mod normal fără restricții de format.',
  'settings.mode.adhdHint': 'Răspunsuri scurte și structurate. Fără text lung.',
  'settings.floatingOrb': 'ORB PLUTITOR',
  'settings.on': 'ON',
  'settings.off': 'OFF',
  'settings.orbSize': 'MĂRIME',
  'settings.orbSize.small': 'Mic',
  'settings.orbSize.medium': 'Mediu',
  'settings.orbSize.large': 'Mare',
  'settings.orbEnabledHint': 'Apare când minimizezi Wispucci AI.',
  'settings.orbDisabledHint': 'Orbul este dezactivat.',
  'settings.browserMode': 'MOD BROWSER',
  'settings.browserModeHint': 'Aici orbul desktop este înlocuit de orbul din pagină și UI-ul browserului. Toggle-urile de overlay sunt ascunse pentru că acest build rulează într-un tab normal.',
  'settings.plans': 'PLANURI',
  'settings.plansHint': 'Free și Premium sunt separate clar: vezi limitele și costurile fără panoul dev.',
  'settings.devTitle': 'DEVELOPER',
  'settings.devButton': 'DEV FULL ACCESS',
  'settings.devHint': 'Folosește asta doar pentru testare. Elimină limitele planului și activează controalele de skip pentru lecții și module blocate.',
  'settings.devStatus.dev': 'DEV FULL ACCESS',
  'settings.devStatus.premium': 'PREMIUM ACTIV',
  'settings.devStatus.free': 'FREE ACTIV',
  'settings.telemetry': 'TELEMETRIE',
  'settings.averageShort': 'med',
  'settings.requestsShort': 'cer.',
  'settings.dangerZone': 'ZONĂ DE PERICOL',
  'settings.dangerZoneHint': 'Pornește de la zero. Asta șterge profilul local, onboarding-ul, task-urile, chat-urile, cursurile, flashcard-urile, memoriile, streak-ul, XP-ul și progresul din jocuri.',
  'settings.resetButton': 'ȘTERGE PROFILUL ȘI REIA DE LA ZERO',
  'settings.resetting': 'SE RESETEAZĂ PROFILUL...',
  'settings.versionPrivate': 'private',
  'settings.confirmReset': 'Ștergi profilul și tot progresul local? Asta va elimina task-urile, istoricul chat-ului, cursurile, flashcard-urile, memoriile, progresul din jocuri, streak-ul, XP-ul și va întoarce aplicația la onboarding.',
  'settings.resetError': 'Profilul nu a putut fi resetat acum. Încearcă din nou.',
  'settings.tier.freeNote': 'Compact și accesibil: aproximativ o treime din profunzimea Premium',
  'settings.tier.premiumNote': 'Mai profund și mai puternic: aproximativ 3x spațiu și profunzime',
  'sidebar.todoCount': '{count} de făcut',
  'sidebar.doneCount': '{count} făcute',
  'sidebar.emptyHint': 'Spune-i lui AURA ce ai de făcut',
  'sidebar.streakDays': '{count} zile streak',
  'sidebar.streak.start': 'Hai să începem!',
  'sidebar.streak.keepUp': 'Ține-o tot așa!',
  'sidebar.streak.onFire': 'Ești în flăcări!',
  'sidebar.streak.legendary': 'Legendar!',
  'sidebar.streak.master': 'MAESTRU ABSOLUT!',
  'sidebar.badges': 'Badge-uri',
  'sidebar.achievements': 'Realizări',
  'sidebar.nextLevelCourses': 'Nivelul următor la {count} cursuri',
  'sidebar.nextLevelWords': 'Nivelul următor la {count} cuvinte',
  'sidebar.nextLevelMinutes': 'Nivelul următor la {count} minute',
  'sidebar.adhdModeActive': 'Modul ADHD este activ',
  'sidebar.quickToggle': 'Ctrl+Shift+A - comutare rapidă',
  'errorBoundary.title': 'Ceva nu a mers bine',
  'errorBoundary.retry': 'Încearcă din nou',
  'errorBoundary.unknown': 'Eroare necunoscută',
  'game.score': 'Scor: {score}',
  'game.pointsAward': '+{points} puncte',
  'game.backToGames': 'Înapoi la jocuri',
  'game.correctCount': '{count} corecte',
  'game.roundsCorrect': '{correct}/{total} runde corecte',
  'game.answeredCount': '{answered}/{total} răspunse',
  'game.averageMs': 'Medie: {ms}ms',
  'game.roundProgress': 'Runda {current}/{total}',
  'game.quit': 'Ieși',
  'game.timeShort': '{seconds}s',
  'game.math.success': 'Foarte bine!',
  'game.math.fail': 'Joc terminat',
  'game.memory.complete': 'Memoria s-a încheiat!',
  'game.memory.memorize': 'Memorează tile-urile!',
  'game.memory.tapRemember': 'Apasă tile-urile pe care ți le amintești',
  'game.memory.submit': 'Trimite ({count} selectate)',
  'game.reaction.complete': 'Reacția s-a încheiat!',
  'game.reaction.wait': 'Așteaptă...',
  'game.reaction.tap': 'APASĂ!',
  'game.reaction.tooEarly': 'Prea devreme!',
  'game.reaction.waitGreen': 'Așteaptă semnalul verde...',
  'game.reaction.clickNow': 'Apasă ACUM!',
  'game.reaction.waitNext': 'Așteaptă semnalul data viitoare',
  'game.reaction.feedbackAmazing': 'Excelent!',
  'game.reaction.feedbackGood': 'Bine!',
  'game.reaction.feedbackKeepTrying': 'Continuă să încerci!',
  'game.word.complete': 'Cuvintele s-au încheiat!',
  'game.word.unscramble': 'Descurcă cuvântul',
  'game.word.answerPlaceholder': 'Răspunsul tău...',
  'game.word.skip': 'Sari peste cuvânt',
  'game.pattern.complete': 'Pattern-ul s-a încheiat!',
  'game.pattern.prompt': 'Ce urmează în secvență?',
  'game.stroop.complete': 'Stroop s-a încheiat!',
  'game.stroop.question': 'Ce CULOARE are textul afișat?',
  'game.stroop.ignore': '(ignoră ce spune cuvântul)',
  'lessonQuiz.blockedStart': 'Quiz-ul nu poate fi pornit acum pentru această lecție.',
  'lessonQuiz.loading': 'GENEREZ QUIZ-UL...',
  'lessonQuiz.passedTitle': 'QUIZ TRECUT!',
  'lessonQuiz.passedBody1': 'AI TRECUT TESTUL DE REAMINTIRE. MAI A RĂMAS O PRACTICĂ SCURTĂ CA SĂ ÎNCHIZI LECȚIA.',
  'lessonQuiz.passedBody2': 'QUIZ-UL VERIFICĂ DACĂ RECUNOȘTI. PRACTICA VERIFICĂ DACĂ POȚI FOLOSI.',
  'lessonQuiz.afterPractice': 'DUPĂ PRACTICĂ',
  'lessonQuiz.enterPractice': 'INTRĂ ÎN PRACTICĂ',
  'lessonQuiz.failedTitle': 'AI NEVOIE DE REVIEW!',
  'lessonQuiz.failedBody': 'AI GREȘIT {count} {label}. REPARĂ MAI ÎNTÂI REAMINTIREA, APOI AJUNGI LA PRACTICĂ.',
  'lessonQuiz.failedBody2': 'DUPĂ CE RECITEȘTI LECȚIA, ÎNCERCAREA URMĂTOARE VA PREGĂTI UN SET NOU ȘI SCURT DE ÎNTREBĂRI.',
  'lessonQuiz.questionSingular': 'ÎNTREBARE',
  'lessonQuiz.questionPlural': 'ÎNTREBĂRI',
  'lessonQuiz.rereadLesson': 'RECITEȘTE LECȚIA',
  'lessonQuiz.backToModule': 'ÎNAPOI LA MODUL',
  'lessonQuiz.backToLesson': 'ÎNAPOI LA LECȚIE',
  'lessonQuiz.blockedTitle': 'QUIZ BLOCAT TEMPORAR',
  'lessonQuiz.correct': 'CORECT!',
  'lessonQuiz.seeResult': 'VEZI REZULTATUL',
  'lessonQuiz.next': 'URMĂTORUL',
  'lessonQuiz.wrong': 'GREȘIT!',
  'lessonQuiz.correctAnswer': 'RĂSPUNS CORECT:',
  'lessonQuiz.reminder': 'REAMINTIRE',
  'lessonQuiz.hintFallback': 'Recitește atent lecția — răspunsul este în conținutul lecției.',
  'lessonQuiz.continueQuiz': 'CONTINUĂ QUIZ-UL',
  'lessonQuiz.header': 'QUIZ · LECȚIA {num}',
  'lessonQuiz.answerPlaceholder': 'Scrie răspunsul...',
  'lessonQuiz.checkAnswer': 'VERIFICĂ RĂSPUNSUL',
  'lessonQuiz.back': '← ÎNAPOI',
}
