import type { StringCatalog } from '../i18n'

export const strings: StringCatalog = {
  // ─── Onboarding ────────────────────────────────────────────────────────────
  'onboarding.hello': 'Привет! Я Wispucci AI.',
  'onboarding.subtitle': 'Твой персональный ассистент для фокуса и прогресса.\nВсё работает локально — никто не видит наших разговоров.',
  'onboarding.namePlaceholder': 'Как тебя зовут?',
  'onboarding.continue': 'Продолжить',
  'onboarding.importantQuestion': '{name}, важный вопрос.',
  'onboarding.adhdQuestion': 'У тебя СДВГ или проблемы с мотивацией/концентрацией?',
  'onboarding.adhdHint': 'Это поможет мне быть мягче и адаптивнее с тобой.',
  'onboarding.adhdYes': 'Да, мне нужен эмпатичный режим',
  'onboarding.adhdNo': 'Нет, нормальный режим подходит',
  'onboarding.languageTitle': 'Предпочитаемый язык?',
  'onboarding.languageHint': 'Wispucci AI будет отвечать на выбранном языке',
  'onboarding.start': 'Поехали!',
  'onboarding.defaultReward1': 'Любимая музыка 🎵',
  'onboarding.defaultReward2': '5 мин перерыв ☕',
  'onboarding.defaultReward3': 'Смешной мем 😂',

  // ─── Energy Prompt ──────────────────────────────────────────────────────────
  'energy.greeting': 'Доброе утро, {name}!',
  'energy.question': 'Как твой уровень энергии сегодня?',
  'energy.confirm': 'Подтвердить ({level}/10)',
  'energy.skip': 'Пропустить',
  'energy.1': 'Очень плохо',
  'energy.2': 'Плохо',
  'energy.3': 'Слабо',
  'energy.4': 'Так себе',
  'energy.5': 'Нормально',
  'energy.6': 'Неплохо',
  'energy.7': 'Хорошо',
  'energy.8': 'Очень хорошо',
  'energy.9': 'Отлично',
  'energy.10': 'МАКСИМУМ!',

  // ─── Greetings (time of day) ───────────────────────────────────────────────
  'greeting.night': 'Доброй ночи, {name}.',
  'greeting.morning': 'Доброе утро, {name}.',
  'greeting.afternoon': 'Добрый день, {name}.',
  'greeting.evening': 'Добрый вечер, {name}.',

  // ─── Floating Menu ─────────────────────────────────────────────────────────
  'menu.tasks': 'Задачи',
  'menu.games': 'Игры',
  'menu.focus': 'Фокус',
  'menu.teacher': 'Учитель',
  'menu.memory': 'Память',
  'menu.achievements': 'Достижения',
  'menu.settings': 'Настройки',
  'menu.friends': 'Друзья',

  // ─── Sidebar ───────────────────────────────────────────────────────────────
  'sidebar.tasks': 'Задачи',
  'sidebar.stats': 'Стат.',
  'sidebar.newTask': 'Новая задача...',
  'sidebar.noTasks': 'Задач пока нет. Добавь одну!',

  // ─── Chat ──────────────────────────────────────────────────────────────────
  'chat.placeholder': 'Напиши сообщение...',
  'chat.welcome': 'Привет, я Wispucci AI — твой персональный ассистент для фокуса. Спроси что угодно, скинь код или просто скажи, как ты себя чувствуешь.',
  'chat.thinking': 'Думаю...',
  'chat.error': 'Что-то пошло не так. Попробуй ещё раз.',
  'chat.limitReached': 'Лимит сообщений на сегодня исчерпан. Возвращайся завтра или обнови до Premium для безлимитного чата.',

  // ─── Course Creator ────────────────────────────────────────────────────────
  'creator.title': 'Создать курс',
  'creator.placeholder': 'Что хочешь изучить?',
  'creator.generate': 'Сгенерировать',
  'creator.generating': 'Генерация...',
  'creator.done': 'Курс создан!',
  'creator.goToCourse': 'Перейти к курсу',
  'creator.blocked': 'Не удалось сгенерировать курс прямо сейчас.',
  'creator.back': '← Назад',

  // ─── Course View ───────────────────────────────────────────────────────────
  'course.modules': 'Модули',
  'course.lessons': 'Уроки',
  'course.completed': 'Завершён',
  'course.locked': 'Заблокирован',
  'course.startLesson': 'Начать урок',
  'course.continueLesson': 'Продолжить',
  'course.back': '← Назад к курсам',
  'course.noContent': 'Контента пока нет.',

  // ─── Lesson Viewer / Quiz ──────────────────────────────────────────────────
  'lesson.loading': 'Подготовка урока...',
  'lesson.readConfirm': 'Я ПРОЧИТАЛ(А)',
  'lesson.startTest': 'Начать тест',
  'lesson.quiz.correct': 'Правильно!',
  'lesson.quiz.wrong': 'Не совсем.',
  'lesson.quiz.next': 'Дальше',
  'lesson.quiz.finish': 'Завершить',
  'lesson.quiz.score': 'Результат: {score}/{total}',

  // ─── Teacher Mode ──────────────────────────────────────────────────────────
  'teacher.preparing': 'Ещё готовлю объяснение учителя...',
  'teacher.readConfirm': 'Прочитал(а) — начать тест',
  'teacher.limitNotice': 'Лимит достигнут',
  'teacher.back': '← Назад',

  // ─── Lesson Support Panel ──────────────────────────────────────────────────
  'support.howWell': 'Насколько хорошо ты понял(а)?',
  'support.score': '{score}/10',
  'support.clarify': 'Задать вопрос',
  'support.clarifyPlaceholder': 'Что было непонятно?',
  'support.flashcards': 'Карточки',
  'support.continueTest': 'Продолжить к тесту',
  'support.startTest': 'Начать тест',
  'support.needScore7': 'Нужно минимум 7/10 чтобы продолжить.',
  'support.recallTitle': 'Быстрый вспомни',

  // ─── Flashcards ────────────────────────────────────────────────────────────
  'flashcard.noCards': 'Нет карточек',
  'flashcard.back': '← Назад',
  'flashcard.tap': 'Нажми чтобы открыть',
  'flashcard.easy': 'Легко ✅',
  'flashcard.medium': 'Средне 🤔',
  'flashcard.hard': 'Не знал(а) 😅',
  'flashcard.done': 'Сессия завершена!',
  'flashcard.accuracy': '{percent}% точность',

  // ─── Achievements ──────────────────────────────────────────────────────────
  'achievements.title': 'Достижения',
  'achievements.subtitle': 'Точный прогресс до следующего разблокирования',
  'achievements.level': 'Уровень {level}',
  'achievements.levelLabel': 'УРОВЕНЬ',
  'achievements.xp': '{xp} XP',
  'achievements.streak': '{days} дней подряд',
  'achievements.lessons': '{count} уроков',
  'achievements.courses': '{count} курсов',
  'achievements.words': '{count} слов',
  'achievements.time': '{minutes} мин',
  'achievements.nextMilestone': 'Далее: {target}',
  'achievements.lessonsTrack': 'УРОКИ',
  'achievements.lessonsUnit': 'уроков',
  'achievements.lessonsLeft': '{count} уроков до следующей вехи',
  'achievements.milestoneHit': 'Веха достигнута. Следующая через {size} уроков.',
  'achievements.coursesTrack': 'КУРСЫ',
  'achievements.coursesUnit': 'курсов',
  'achievements.coursesLeft': '{count} курсов до следующего достижения',
  'achievements.wordsTrack': 'СЛОВА',
  'achievements.wordsUnit': 'слов',
  'achievements.wordsLeft': '{count} слов до следующего достижения',
  'achievements.timeTrack': 'ВРЕМЯ',
  'achievements.timeUnit': 'минут',
  'achievements.timeLeft': '{count} минут до следующего достижения',
  'achievements.allUnlocked': 'Все достижения разблокированы',
  'achievements.totalBadges': 'Всего значков: {count}',
  'achievements.bonusXP': 'Бонус XP: {xp}',

  // ─── Settings ──────────────────────────────────────────────────────────────
  'settings.title': 'Настройки',
  'settings.plan': 'План',
  'settings.activeWindow': 'Активное окно',
  'settings.coursesPerMonth': 'КУРСЫ / МЕСЯЦ',
  'settings.coursesPer2h': 'КУРСЫ / 2Ч',
  'settings.chatPerDay': 'ЧАТ / ДЕНЬ',
  'settings.lessonsPer2h': 'УРОКИ / 2Ч',
  'settings.lessonsPerMonth': 'УРОКИ / МЕСЯЦ',
  'settings.flashcards': 'КАРТОЧКИ',
  'settings.pdfExport': 'PDF ЭКСПОРТ',
  'settings.yes': 'ДА',
  'settings.no': 'НЕТ',
  'settings.unlimited': '∞',
  'settings.active': 'АКТИВЕН',
  'settings.planLabel': 'ПЛАН',
  'settings.tokenSources': 'ИСТОЧНИКИ РАСХОДА ТОКЕНОВ',
  'settings.psychFrame': 'ПСИХОЛОГИЧЕСКИЙ ФРЕЙМИНГ',
  'settings.noTraffic': 'Пока недостаточно AI-трафика для сравнения.',
  'settings.clearChat': 'Очистить историю чата',
  'settings.clearConfirm': 'Очищено!',
  'settings.language': 'Язык',
  'settings.tier.free': 'Бесплатный',
  'settings.tier.premium': 'Премиум',

  // ─── Top Indicator ─────────────────────────────────────────────────────────
  'indicator.chatExhausted': 'ЧАТ ИСЧЕРПАН',
  'indicator.chatRemaining': 'ЧАТ {remaining} / {limit} ОСТАЛОСЬ',
  'indicator.messagesLeft': 'Осталось {count} сообщ. сегодня',
  'indicator.messagesExhausted': 'ЧАТ ИСЧЕРПАН · сброс завтра',
  'indicator.lessonMilestoneHit': 'Мини-веха достигнута',
  'indicator.lessonsUntilMilestone': '{count} уроков до следующей вехи',

  // ─── Focus Mode ────────────────────────────────────────────────────────────
  'focus.deepWork': 'Глубокая работа',
  'focus.sprint': 'Спринт',
  'focus.flow': 'Поток',
  'focus.custom': 'Свой',
  'focus.start': 'Старт',
  'focus.pause': 'Пауза',
  'focus.resume': 'Продолжить',
  'focus.stop': 'Стоп',
  'focus.sessionComplete': 'Сессия завершена!',
  'focus.back': '← Назад',

  // ─── Pomodoro ──────────────────────────────────────────────────────────────
  'pomodoro.work': 'Время фокуса',
  'pomodoro.break': 'Перерыв',
  'pomodoro.sessions': '{count} сессий',
  'pomodoro.wellDone': 'Отлично! Сделай перерыв.',
  'pomodoro.breakOver': 'Перерыв закончился. Продолжаем!',
  'pomodoro.focusActivated': 'Режим фокуса активирован. За работу!',
  'pomodoro.breakStarted': 'Перерыв начался.',
  'pomodoro.back': '← Назад',

  // ─── Body Doubling ─────────────────────────────────────────────────────────
  'companion.together': 'вместе',
  'companion.exit': '← выйти',
  'companion.main': 'Мы вместе, {name}.',
  'companion.mainNoName': 'Мы вместе.',
  'companion.sub': 'Работай спокойно. Я рядом.',
  'companion.phrases.0': 'Я рядом',
  'companion.phrases.1': 'Ты молодец',
  'companion.phrases.2': 'Дыши',
  'companion.phrases.3': 'Ты не один',
  'companion.phrases.4': 'Отдохни если нужно',
  'companion.phrases.5': 'Ты на верном пути',
  'companion.phrases.6': 'Всё что ты делаешь важно',
  'companion.phrases.7': 'Я здесь',
  'companion.phrases.8': 'Думаю о тебе',
  'companion.phrases.9': 'Не торопись',

  // ─── Dopamine Menu ─────────────────────────────────────────────────────────
  'dopamine.youtube': '15 мин YouTube',
  'dopamine.game': '20 мин игр',
  'dopamine.walk': 'Прогулка',
  'dopamine.snack': 'Любимый перекус',
  'dopamine.music': 'Послушать музыку',
  'dopamine.social': '10 мин соцсети',
  'dopamine.nap': '20 мин сон',
  'dopamine.draw': 'Порисовать',
  'dopamine.stretch': 'Растяжка / Йога',
  'dopamine.chat': 'Поговорить с кем-то',
  'dopamine.coffee': 'Перерыв на кофе',
  'dopamine.custom': 'Своя награда',
  'dopamine.enjoy': 'Наслаждайся!',
  'dopamine.deserved': 'Ты заслужил(а). Отдыхай.',
  'dopamine.backToWork': 'Обратно к работе',
  'dopamine.congrats': 'Поздравляем!',

  // ─── Career Mirror ─────────────────────────────────────────────────────────
  'career.title': 'Зеркало карьеры',
  'career.loading': 'Генерирую проекцию...',
  'career.back': '← Назад',

  // ─── Daily Summary ─────────────────────────────────────────────────────────
  'daily.title': 'Итоги дня',
  'daily.loading': 'Генерирую сводку...',
  'daily.back': '← Назад',

  // ─── Brain Games ───────────────────────────────────────────────────────────
  'games.title': 'Тренировки для мозга',
  'games.back': '← Назад',
  'games.mathSpeed': 'Скорость счёта',
  'games.memoryTiles': 'Плитки памяти',
  'games.patternMatch': 'Подбор паттерна',
  'games.reactionTime': 'Время реакции',
  'games.wordScramble': 'Перемешанные слова',
  'games.colorStroop': 'Цветовой Струп',
  'games.todayPoints': 'Сегодня',
  'games.totalPoints': 'Всего',
  'games.leaderboard': 'Таблица лидеров',
  'games.difficulty': 'Сложность',

  // ─── Memory Panel ──────────────────────────────────────────────────────────
  'memory.stable': 'Стабильные',
  'memory.stableHint': 'Факты которые остаются (кто ты, что любишь, цели)',
  'memory.moments': 'Моменты',
  'memory.momentsHint': 'Эмоционально отмеченные моменты (победы, трудности, открытия)',
  'memory.session': 'Сессия',
  'memory.sessionHint': 'Контекст из этой сессии (исчезнет через 6ч если не важно)',
  'memory.all': 'Все',
  'memory.add': '+ Добавить',
  'memory.addNew': 'Добавить',
  'memory.remember': 'Запомнить',
  'memory.placeholder': 'Пр: Лучше всего работаю утром · Хочу дочитать книгу до понедельника · Стрессуют большие дедлайны',
  'memory.title': 'Наша память',
  'memory.subtitle': 'Здесь ты видишь всё, что я помню о тебе. Это не секрет — это твоё. Можешь удалить что угодно, когда угодно.',
  'memory.tagline': 'что я помню',
  'memory.empty': 'Воспоминаний пока нет.',

  // ─── Levels ────────────────────────────────────────────────────────────────
  'level.1': 'Новичок',
  'level.2': 'Любопытный',
  'level.3': 'Стабильный',
  'level.4': 'Сфокусированный',
  'level.5': 'Преданный',
  'level.6': 'Продвинутый',
  'level.7': 'Эксперт',
  'level.8': 'Мастер',

  // ─── Badges ────────────────────────────────────────────────────────────────
  'badge.first_session': 'Первая сессия',
  'badge.streak_3': '3 дня подряд',
  'badge.streak_7': '7 дней огня',
  'badge.streak_30': '30 дней — легенда',
  'badge.level_3': 'Достиг уровня 3',
  'badge.level_5': 'Достиг уровня 5',
  'badge.xp_500': '500 XP',
  'badge.xp_1000': '1000 XP',
  'badge.first_course': 'Начал первый курс',
  'badge.course_complete': 'Завершил курс',
  'badge.course_1': 'Завершил 1 курс',
  'badge.course_3': 'Завершил 3 курса',
  'badge.course_5': 'Завершил 5 курсов',
  'badge.course_10': 'Завершил 10 курсов',
  'badge.words_200': 'Набрал 200 слов',
  'badge.words_1000': 'Набрал 1000 слов',
  'badge.words_5000': 'Набрал 5000 слов',
  'badge.words_15000': 'Набрал 15000 слов',
  'badge.time_30': '30 минут в приложении',
  'badge.time_120': '2 часа в приложении',
  'badge.time_600': '10 часов в приложении',
  'badge.time_1800': '30 часов в приложении',

  // ─── Moods ─────────────────────────────────────────────────────────────────
  'mood.happy': 'Счастливый',
  'mood.excited': 'Взволнованный',
  'mood.think': 'Задумчивый',
  'mood.sleepy': 'Сонный',
  'mood.sad': 'Грустный',
  'mood.love': 'Благодарный',
  'mood.focus': 'Сфокусированный',

  // ─── Crisis ────────────────────────────────────────────────────────────────
  'crisis.response': `Я понимаю, что ты переживаешь очень тяжёлый момент. Ты не один/одна в этом.

Пожалуйста, позвони СЕЙЧАС по одному из этих номеров — обученные люди слушают, бесплатно, круглосуточно:
• Россия: 8-800-2000-122 (телефон доверия)
• Дети и подростки: 8-800-2000-122
• Международный: findahelpline.com

Тебе не нужно проходить через это в одиночку. Эти люди обучены помогать.`,

  // ─── Tier Limit Messages ───────────────────────────────────────────────────
  'limits.courseWindow': '🧠 АКТИВНАЯ КОНСОЛИДАЦИЯ\n\nТы уже создал(а) {limit} курсов за последние 2 часа на плане {label}. Притормози и дай существующим курсам устояться.\n\nВозвращайся через {reset} или продолжи один из начатых курсов.',
  'limits.courseMonth': '📚 МЕСЯЧНЫЙ ЛИМИТ КУРСОВ\n\nТы достиг(ла) месячного лимита в {limit} курсов на плане {label}.\n\nМожешь продолжать существующие курсы, новые слоты появятся в следующем месяце.',
  'limits.lessonWindow': '📚 ПАУЗА КОНСОЛИДАЦИИ\n\nТы уже открыл(а) {limit} новых уроков за последние 2 часа на плане {label}. Продолжай начатое и возвращайся после сброса.\n\nСледующий слот откроется через {reset}.',
  'limits.lessonMonth': '🧩 МЕСЯЧНЫЙ ЛИМИТ УРОКОВ\n\nТы достиг(ла) месячного лимита в {limit} уроков на плане {label}.\n\nМожешь продолжать существующие уроки, новые слоты появятся в следующем месяце.',
  'limits.chatBudget': '💬 ЛИМИТ ЧАТА ДОСТИГНУТ\n\nТы использовал(а) все {limit} ежедневных сообщений на плане {label}.\n\nСообщения обновятся завтра. Обнови до Premium для безлимитного чата.',
  'limits.chatExhausted': 'ЧАТ ИСЧЕРПАН · сброс завтра',

  // ─── Tier Notes ────────────────────────────────────────────────────────────
  'tierNote.courses': 'У курсов два ограничения: темп за 2 часа и объём за месяц. Первое останавливает импульсивный спам, второе контролирует экономику.',
  'tierNote.chat': 'Чат — единственный блокирующий AI-бюджет. Курсы и уроки используют телеметрию для учёта стоимости, а не блокировку токенов.',
  'tierNote.lessons': 'У уроков есть лимит на 2 часа и на месяц. Повторный вход в тот же урок не тратит новый слот.',
  'tierNote.flashcardsUnlimited': 'Этот план не ограничивает общее количество карточек.',
  'tierNote.flashcardsLimited': 'Лимит карточек сохраняет систему плотной и повторяемой, а не складом забытых карт.',
  'tierNote.pdfExportYes': 'Экспорт PDF остаётся активным когда поверхность экспорта открыта в UI.',
  'tierNote.pdfExportNo': 'Экспорт PDF заблокирован на этом плане как фича удобства, а не базовая фича обучения.',

  // ─── Overlay / Tray ────────────────────────────────────────────────────────
  'overlay.newLesson': 'Давай выучим что-то новое!',
  'overlay.progress': 'Прогресс делается шаг за шагом.',
  'overlay.youGotThis': 'У тебя получится!',
  'overlay.keepGoing': 'Продолжай!',
  'tray.show': 'Показать Wispucci AI',
  'tray.quit': 'Выход',

  // ─── Game colors (Stroop) ──────────────────────────────────────────────────
  'color.red': 'КРАСНЫЙ',
  'color.blue': 'СИНИЙ',
  'color.green': 'ЗЕЛЁНЫЙ',
  'color.yellow': 'ЖЁЛТЫЙ',
  'color.orange': 'ОРАНЖЕВЫЙ',

  // ─── Themes ────────────────────────────────────────────────────────────────
  'theme.forest': 'Лес',

  // ─── Common ────────────────────────────────────────────────────────────────
  'common.back': '← Назад',
  'common.close': 'Закрыть',
  'common.save': 'Сохранить',
  'common.cancel': 'Отмена',
  'common.loading': 'Загрузка...',
  'common.noData': 'Данных пока нет.',

  // ─── AI Error ──────────────────────────────────────────────────────────────
  'aiError.title': 'Сервис недоступен',
  'aiError.subtitle': 'Введите API-ключ для продолжения.',
  'aiError.invalidKey': 'Недействительный ключ или API недоступен',
  'aiError.saveError': 'Ошибка сохранения',
  'aiError.save': 'Сохранить и подключить',
  'aiError.recheck': 'Проверить без нового ключа',
  'common.hoursShort': 'ч',
  'common.minutesShort': 'м',
  'app.badgeUnlocked': 'Достижение получено!',
  'app.welcomeBackFreeze': 'С возвращением, {name}. Мы сохранили серию — использована заморозка.',
  'app.welcomeBackReset': 'С возвращением, {name}. Не переживай из-за серии — давай начнём заново вместе.',
  'app.greeting.night': 'Доброй ночи',
  'app.greeting.morning': 'Доброе утро',
  'app.greeting.afternoon': 'Добрый день',
  'app.greeting.evening': 'Добрый вечер',
  'app.greeting.intro': '{greeting}, {name}! Я Wispucci AI. Нажми на меня для меню или просто напиши что-нибудь.',
  'app.flashcards.noneDue': 'Сейчас нет карточек для повторения.',
  'app.flashcards.openError': 'Сейчас не удалось открыть повторение.',
  'app.quickStart.title': 'Быстрый старт',
  'app.quickStart.organize': 'Хорошо. Начни с одной видимой задачи и сделай день конкретным. Я открыл доску задач.',
  'app.quickStart.learn': 'Хорошо. Выбери одну тему и иди по одному пути. Я открыл создание курса, чтобы начать чисто.',
  'app.quickStart.focus': 'Хорошо. Сначала защити один блок внимания. Я открыл Focus Mode, чтобы быстро набрать темп.',
  'app.firstCourse.title': 'Первый курс',
  'app.tutorialComplete': 'Хорошо. Твой первый курс уже жив. Иди по пути курса, задавай вопросы через нижнюю строку и открывай меню орба, когда нужен другой инструмент.',
  'app.levelUpTitle': 'Новый уровень!',
  'app.levelReached': 'Ты достиг(ла) уровня {level}',
  'app.localWeb': 'local web',
  'app.inputPlaceholder': 'Напиши что-нибудь для Wispucci AI...',
  'chatAction.openTasks': 'Открыть задачи',
  'chatAction.openCourses': 'Открыть курсы',
  'chatAction.openCreator': 'Открыть создание',
  'chatAction.openFlashcards': 'Повторить карточки',
  'chatAction.openCourse': 'Продолжить курс',
  'chatAction.openTeacher': 'Открыть режим Teacher',
  'chatAction.open': 'Открыть',
  'tutorial.kicker': 'Пошаговый старт',
  'tutorial.introTitle': 'Сначала создадим что-то реальное.',
  'tutorial.introDescription': 'Ты назовёшь курс, ответишь на пару быстрых вопросов, а потом посадишь его и сразу перейдёшь к меню орба.',
  'tutorial.introDetail': 'Коротко и просто. Без длинного тура.',
  'tutorial.introStatus': 'Сначала курс. Потом меню.',
  'tutorial.introAction': 'Начать',
  'tutorial.introHelper': 'Это вступление специально короткое.',
  'tutorial.step1': 'Шаг 1',
  'tutorial.step1TitleType': 'Нажми сюда и введи тему.',
  'tutorial.step1TitleContinue': 'Теперь нажми «Продолжить».',
  'tutorial.step1TitleQuestions': 'Ответь на эти быстрые вопросы.',
  'tutorial.step1TitlePlant': 'Теперь посади курс.',
  'tutorial.step1DescriptionType': 'Выбери любую реальную тему. После этого экран сам прокрутится к кнопке «Продолжить».',
  'tutorial.step1DescriptionContinue': 'Хорошо. Запусти короткий этап настройки. После «Продолжить» туториал будет вести тебя уже по окну вопросов.',
  'tutorial.step1DescriptionQuestions': 'Ответь на короткие вопросы, чтобы Wispucci подстроил маршрут курса ещё до старта генерации.',
  'tutorial.step1DescriptionPlant': 'Настройка готова. Посади курс, и туториал сразу перейдёт дальше.',
  'tutorial.step1Detail': 'Теперь туториал остаётся с тобой на коротком intake-этапе и не заставляет ждать долгую генерацию.',
  'tutorial.step1DetailQuestions': 'Можно нажимать на готовые примеры или вписать свой короткий ответ.',
  'tutorial.step1StatusMoving': 'Переходим к шагу с орбом...',
  'tutorial.step1StatusContinue': 'Ждём «Продолжить»...',
  'tutorial.step1StatusQuestions': 'Ждём ответы...',
  'tutorial.step1StatusPlant': 'Ждём запуск курса...',
  'tutorial.step1StatusTopic': 'Ждём тему...',
  'tutorial.step1HelperOpen': 'Снова открой создание курса, если окно закрылось.',
  'tutorial.step1HelperFollow': 'Следуй за подсвеченным элементом.',
  'tutorial.step1ActionOpen': 'Открыть создание курса',
  'tutorial.step2': 'Шаг 2',
  'tutorial.step2Title': 'Теперь нажми на орб.',
  'tutorial.step2Description': 'После клика по орбу и открытия меню туториал закончится.',
  'tutorial.step2Detail': 'Теперь это весь первый сценарий запуска.',
  'tutorial.step2StatusOpen': 'Меню открыто.',
  'tutorial.step2StatusWait': 'Ждём клик по орбу...',
  'tutorial.step2HelperFallback': 'Если орб плохо виден, используй запасную кнопку.',
  'tutorial.step2HelperDone': 'Хорошо. Гайд завершён.',
  'tutorial.step2ActionOpen': 'Открыть меню орба',
  'creator.heroTitle': 'Чему ты хочешь научиться?',
  'creator.heroSubtitle': 'Посади идею — Wispucci AI превратит её в дерево знаний за 47 секунд.',
  'creator.familiarityPrompt': 'Насколько ты уже знаком(а) с этой темой?',
  'creator.familiarity.new.label': 'Новичок',
  'creator.familiarity.new.note': 'начать с нуля',
  'creator.familiarity.rusty.label': 'Подзабыл(а)',
  'creator.familiarity.rusty.note': 'я уже видел(а) это раньше',
  'creator.familiarity.comfortable.label': 'Уверенно',
  'creator.familiarity.comfortable.note': 'знаю базу',
  'creator.familiarity.strong.label': 'Сильный уровень',
  'creator.familiarity.strong.note': 'пропусти очевидную базу',
  'creator.familiarity.unsure.label': 'Не уверен(а)',
  'creator.familiarity.unsure.note': 'определи за меня',
  'creator.continue': 'Продолжить',
  'creator.preparingQuestions': 'Готовлю вопросы...',
  'creator.intakeTitle': 'Пара быстрых вопросов',
  'creator.intakeSubtitle': 'Wispucci AI подстроит маршрут перед тем, как курс начнёт расти.',
  'creator.intakeProgressSummaryLabel': 'Под что курс уже подстраивается',
  'creator.intakeReadySummaryLabel': 'Текущее направление курса',
  'creator.editTopic': '← Изменить тему',
  'creator.generateCourse': 'Посадить курс с Wispucci AI',
  'creator.planting': 'Сажаем знания...',
  'creator.startedTitle': 'Семя посажено',
  'creator.startedSubtitle': 'Курс растёт в фоне.\nМожно уже вернуться к списку курсов.',
  'creator.startedAction': 'Открыть список курсов',
  'creator.doneTitle': 'Дерево расцвело!',
  'creator.doneSubtitle': 'Уроки и темы\nуже укоренены ✓',
  'creator.explore': 'Открыть курс',
  'creator.blockedTitle': 'Консолидация перед следующим курсом',
  'courseList.title': 'Мои курсы',
  'courseList.count': '{count} курсов',
  'courseList.create': 'Посадить новый курс',
  'courseList.cooldownHint': 'Новый курс можно создавать раз в 2 часа',
  'courseList.nextAvailable': 'Следующий слот',
  'courseList.growing': 'Растёт',
  'courseList.bloomed': 'Расцвёл',
  'courseList.generatingHint': 'Растёт в фоне',
  'courseList.failedHint': 'Генерация остановилась до готовности курса',
  'courseList.failedStatus': 'ошибка',
  'courseList.teacher': 'Попробовать с учителем',
  'courseList.emptyTitle': 'Пока нет курсов',
  'courseList.emptySubtitle': 'Wispucci AI создаёт персонализированные курсы',
  'courseList.emptyAction': 'Создать первый курс',
  'games.pointsLabel': 'Игровые очки',
  'games.pointsSummary': 'всего {total} · +{today} сегодня · 100 очков = 1 Pro Day',
  'games.redeem': 'Обменять на Pro Day',
  'games.todayBest': 'Лучшее сегодня',
  'games.category.logic': '🧩 Логика',
  'games.category.memory': '🧠 Память',
  'games.category.attention': '👁 Внимание',
  'games.category.speed': '⚡ Скорость',
  'games.desc.mathSpeed': 'Решай примеры до окончания времени',
  'games.desc.memoryTiles': 'Запоминай и повторяй узоры плиток',
  'games.desc.patternMatch': 'Найди следующее число в последовательности',
  'games.desc.reactionTime': 'Кликай как можно быстрее, когда увидишь сигнал',
  'games.desc.wordScramble': 'Собери спрятанные слова',
  'games.desc.colorStroop': 'Называй цвет, а не слово',
  'leaderboard.title': 'Таблица лидеров',
  'leaderboard.totalPoints': 'Всего очков',
  'leaderboard.today': 'Сегодня',
  'leaderboard.proDaysRedeemed': '{count} Pro Days обменяно',
  'leaderboard.redeem': 'Обменять на Pro Day (100 очков)',
  'leaderboard.thisWeek': 'Эта неделя',
  'leaderboard.todayLabel': 'Сегодня',
  'leaderboard.noGames': 'Игры ещё не запускались',
  'leaderboard.best': 'лучший',
  'leaderboard.dailyHint': 'Играй каждый день, чтобы зарабатывать очки. 100 очков = 1 день Pro.',
  'leaderboard.points': 'очков',
  'daily.aiSays': 'Wispucci AI говорит:',
  'daily.feeling': 'Как ты себя чувствуешь?',
  'daily.close': 'Закрыть',
  'daily.streak': 'Серия',
  'daily.xpToday': 'XP',
  'daily.tasks': 'Задачи',
  'daily.games': 'Игры',
  'settings.profileLabel': 'ПРОФИЛЬ',
  'settings.ageGroup': 'ВОЗРАСТНАЯ ГРУППА',
  'settings.ageGroupHint': 'Wispucci AI подбирает примеры и уровень критики под эту группу.',
  'settings.age.under16': 'До 16',
  'settings.age.16to25': '16-25',
  'settings.age.25plus': '25+',
  'settings.age.unknown': 'Не указано',
  'settings.botLanguage': 'ЯЗЫК БОТА',
  'settings.modeLabel': 'РЕЖИМ',
  'settings.mode.standard': 'Стандарт',
  'settings.mode.adhd': 'ADHD',
  'settings.mode.standardHint': 'Обычный режим без ограничений формата.',
  'settings.mode.adhdHint': 'Короткие структурированные ответы. Без длинных текстов.',
  'settings.floatingOrb': 'ПЛАВАЮЩИЙ ОРБ',
  'settings.on': 'ВКЛ',
  'settings.off': 'ВЫКЛ',
  'settings.orbSize': 'РАЗМЕР',
  'settings.orbSize.small': 'Маленький',
  'settings.orbSize.medium': 'Средний',
  'settings.orbSize.large': 'Большой',
  'settings.orbEnabledHint': 'Появляется, когда ты сворачиваешь Wispucci AI.',
  'settings.orbDisabledHint': 'Орб выключен.',
  'settings.browserMode': 'РЕЖИМ БРАУЗЕРА',
  'settings.browserModeHint': 'Здесь плавающий орб заменён встроенным орбом и браузерным UI. Переключатели overlay скрыты, потому что эта сборка работает в обычной вкладке.',
  'settings.plans': 'ПЛАНЫ',
  'settings.plansHint': 'Free и Premium явно разделены: видно лимиты и стоимость без dev-панели.',
  'settings.devTitle': 'РАЗРАБОТЧИК',
  'settings.devButton': 'DEV FULL ACCESS',
  'settings.devHint': 'Используй это только для тестов. Режим снимает лимиты плана и включает кнопки skip для уроков и закрытых модулей.',
  'settings.devStatus.dev': 'ДЕВ БЕЗ ЛИМИТОВ',
  'settings.devStatus.premium': 'PREMIUM АКТИВЕН',
  'settings.devStatus.free': 'FREE АКТИВЕН',
  'settings.telemetry': 'ТЕЛЕМЕТРИЯ',
  'settings.averageShort': 'ср.',
  'settings.requestsShort': 'запр.',
  'settings.dangerZone': 'ОПАСНАЯ ЗОНА',
  'settings.dangerZoneHint': 'Начать с нуля. Это удалит локальный профиль, онбординг, задачи, чаты, курсы, карточки, память, серию, XP и игровой прогресс.',
  'settings.resetButton': 'УДАЛИТЬ ПРОФИЛЬ И НАЧАТЬ ЗАНОВО',
  'settings.resetting': 'СБРОС ПРОФИЛЯ...',
  'settings.versionPrivate': 'private',
  'settings.confirmReset': 'Удалить профиль и весь локальный прогресс? Это удалит задачи, историю чата, курсы, карточки, память, игровой прогресс, серию, XP и вернёт приложение к онбордингу.',
  'settings.resetError': 'Сейчас не удалось сбросить профиль. Попробуй ещё раз.',
  'settings.tier.freeNote': 'Компактно и доступно: примерно треть глубины Premium',
  'settings.tier.premiumNote': 'Глубже и мощнее: примерно в 3 раза больше пространства и глубины',
  'sidebar.todoCount': '{count} в работе',
  'sidebar.doneCount': '{count} сделано',
  'sidebar.emptyHint': 'Скажи AURA, что тебе нужно сделать',
  'sidebar.streakDays': '{count} дней подряд',
  'sidebar.streak.start': 'Начнём!',
  'sidebar.streak.keepUp': 'Так держать!',
  'sidebar.streak.onFire': 'Ты в огне!',
  'sidebar.streak.legendary': 'Легендарно!',
  'sidebar.streak.master': 'АБСОЛЮТНЫЙ МАСТЕР!',
  'sidebar.badges': 'Бейджи',
  'sidebar.achievements': 'Достижения',
  'sidebar.nextLevelCourses': 'Следующий уровень на {count} курсах',
  'sidebar.nextLevelWords': 'Следующий уровень на {count} словах',
  'sidebar.nextLevelMinutes': 'Следующий уровень на {count} минутах',
  'sidebar.adhdModeActive': 'Режим ADHD активен',
  'sidebar.quickToggle': 'Ctrl+Shift+A - быстрое переключение',
  'errorBoundary.title': 'Что-то пошло не так',
  'errorBoundary.retry': 'Попробовать снова',
  'errorBoundary.unknown': 'Неизвестная ошибка',
  'game.score': 'Счёт: {score}',
  'game.pointsAward': '+{points} очков',
  'game.backToGames': 'Назад к играм',
  'game.correctCount': 'верно: {count}',
  'game.roundsCorrect': '{correct}/{total} раундов верно',
  'game.answeredCount': '{answered}/{total} отвечено',
  'game.averageMs': 'Среднее: {ms}мс',
  'game.roundProgress': 'Раунд {current}/{total}',
  'game.quit': 'Выйти',
  'game.timeShort': '{seconds}с',
  'game.math.success': 'Отлично!',
  'game.math.fail': 'Игра окончена',
  'game.memory.complete': 'Память завершена!',
  'game.memory.memorize': 'Запомни плитки!',
  'game.memory.tapRemember': 'Нажми на плитки, которые запомнил(а)',
  'game.memory.submit': 'Отправить ({count} выбрано)',
  'game.reaction.complete': 'Реакция завершена!',
  'game.reaction.wait': 'Жди...',
  'game.reaction.tap': 'ЖМИ!',
  'game.reaction.tooEarly': 'Слишком рано!',
  'game.reaction.waitGreen': 'Жди зелёный сигнал...',
  'game.reaction.clickNow': 'Нажимай СЕЙЧАС!',
  'game.reaction.waitNext': 'В следующий раз дождись сигнала',
  'game.reaction.feedbackAmazing': 'Потрясающе!',
  'game.reaction.feedbackGood': 'Хорошо!',
  'game.reaction.feedbackKeepTrying': 'Продолжай тренироваться!',
  'game.word.complete': 'Слова завершены!',
  'game.word.unscramble': 'Собери слово',
  'game.word.answerPlaceholder': 'Твой ответ...',
  'game.word.skip': 'Пропустить слово',
  'game.pattern.complete': 'Паттерн завершён!',
  'game.pattern.prompt': 'Что идёт следующим в последовательности?',
  'game.stroop.complete': 'Струп завершён!',
  'game.stroop.question': 'Какого ЦВЕТА этот текст?',
  'game.stroop.ignore': '(игнорируй само слово)',
  'lessonQuiz.blockedStart': 'Сейчас не удаётся запустить квиз для этого урока.',
  'lessonQuiz.loading': 'ГЕНЕРИРУЮ КВИЗ...',
  'lessonQuiz.passedTitle': 'КВИЗ ПРОЙДЕН!',
  'lessonQuiz.passedBody1': 'ТЫ ПРОШЁЛ(А) ПРОВЕРКУ НА ВОСПОМИНАНИЕ. ОСТАЛАСЬ КОРОТКАЯ ПРАКТИКА, ЧТОБЫ ЗАКРЫТЬ УРОК.',
  'lessonQuiz.passedBody2': 'КВИЗ ПРОВЕРЯЕТ, УЗНАЁШЬ ЛИ ТЫ МАТЕРИАЛ. ПРАКТИКА ПРОВЕРЯЕТ, УМЕЕШЬ ЛИ ТЫ ЕГО ИСПОЛЬЗОВАТЬ.',
  'lessonQuiz.afterPractice': 'ПОСЛЕ ПРАКТИКИ',
  'lessonQuiz.enterPractice': 'К ПРАКТИКЕ',
  'lessonQuiz.failedTitle': 'НУЖНО ПОВТОРИТЬ!',
  'lessonQuiz.failedBody': 'ТЫ ОШИБСЯ(АСЬ) В {count} {label}. СНАЧАЛА ВОССТАНОВИ ВОСПОМИНАНИЕ, ПОТОМ ДОЙДЁШЬ ДО ПРАКТИКИ.',
  'lessonQuiz.failedBody2': 'ПОСЛЕ ПЕРЕЧТЕНИЯ УРОКА СЛЕДУЮЩАЯ ПОПЫТКА СОБЕРЁТ НОВЫЙ КОРОТКИЙ НАБОР ВОПРОСОВ.',
  'lessonQuiz.questionSingular': 'ВОПРОСЕ',
  'lessonQuiz.questionPlural': 'ВОПРОСАХ',
  'lessonQuiz.rereadLesson': 'ПЕРЕЧИТАТЬ УРОК',
  'lessonQuiz.backToModule': 'НАЗАД К МОДУЛЮ',
  'lessonQuiz.backToLesson': 'НАЗАД К УРОКУ',
  'lessonQuiz.blockedTitle': 'КВИЗ ВРЕМЕННО ЗАБЛОКИРОВАН',
  'lessonQuiz.correct': 'ВЕРНО!',
  'lessonQuiz.seeResult': 'К РЕЗУЛЬТАТУ',
  'lessonQuiz.next': 'ДАЛЬШЕ',
  'lessonQuiz.wrong': 'НЕВЕРНО!',
  'lessonQuiz.correctAnswer': 'ПРАВИЛЬНЫЙ ОТВЕТ:',
  'lessonQuiz.reminder': 'НАПОМИНАНИЕ',
  'lessonQuiz.hintFallback': 'Внимательно перечитай урок — ответ есть в содержании урока.',
  'lessonQuiz.continueQuiz': 'ПРОДОЛЖИТЬ КВИЗ',
  'lessonQuiz.header': 'КВИЗ · УРОК {num}',
  'lessonQuiz.answerPlaceholder': 'Введи ответ...',
  'lessonQuiz.checkAnswer': 'ПРОВЕРИТЬ ОТВЕТ',
  'lessonQuiz.back': '← НАЗАД',
}
